import json
import logging
from pathlib import Path
from typing import Any
from html import unescape

from fastapi import BackgroundTasks, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from app.api.export import (
    build_export_package,
    cleanup_export_later,
    router as export_router,
)
from app.api.optimize import optimize_parsed_product, router as optimize_router


BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"
CACHE_DATA_DIR = BASE_DIR / "static" / "cache_data"
RAW_PAYLOAD_PATH = CACHE_DATA_DIR / "raw_payload.json"
PARSED_PRODUCT_PATH = CACHE_DATA_DIR / "parsed_product.json"
logger = logging.getLogger("easycollect")


class HealthResponse(BaseModel):
    """Describe the health-check response returned by the API.

    Attributes:
        status: Lightweight service status string. The MVP returns ``ok`` when the
            FastAPI application has started correctly.
        service: Stable service identifier used by the browser extension and
            local debugging scripts.
        static_url: Public URL prefix for locally cached preview media mounted by
            FastAPI's ``StaticFiles`` integration.
    """

    status: str
    service: str
    static_url: str


class CollectRequest(BaseModel):
    """Represent raw product data captured by the browser extension.

    Attributes:
        source: Source marketplace identifier, such as ``1688``.
        url: Product detail page URL where the raw payload was captured.
        capturedAt: ISO timestamp generated by the content script.
        dataKey: Matched page data variable name, such as ``__INITIAL_DATA__`` or
            ``__pageData__``.
        title: Best-effort product title extracted by the content script.
        images: Best-effort product image URLs extracted by the content script.
        ai_mode: Whether Kiro Agent copy optimization should run before export.
        raw: Raw frontend JSON object collected from the product page. The Agent
            workflow will reduce and normalize this payload in later steps.
    """

    source: str
    url: str
    capturedAt: str
    dataKey: str | None = None
    title: str | None = None
    images: list[str] = Field(default_factory=list)
    ai_mode: bool = False
    raw: Any


class CollectResponse(BaseModel):
    """Describe the acknowledgement returned after receiving product data.

    Attributes:
        status: Indicates whether the backend accepted the captured payload.
        msg: Human-readable result summary for development feedback.
        title: Parsed product title from the raw 1688 payload.
        images: Parsed product image URLs from the raw 1688 payload.
        price: Parsed product reference price from the raw 1688 payload.
        raw_file: Local debug JSON file path where the latest raw payload is saved.
        parsed_file: Local debug JSON file path for the cleaned product summary.
        download_url: Browser-accessible URL for the generated ERP ZIP package.
        optimized: Whether the export ZIP was built with Kiro Agent copy.
    """

    status: str
    msg: str
    title: str | None = None
    images: list[str] = Field(default_factory=list)
    price: str | int | float | None = None
    raw_file: str | None = None
    parsed_file: str | None = None
    download_url: str | None = None
    optimized: bool = False


def dump_raw_payload(raw: Any) -> Path:
    """Persist the latest raw 1688 payload to a local JSON debug file.

    The file is intentionally overwritten on each capture during the MVP phase so
    developers can inspect the most recent real-world payload shape without
    introducing a database or long-term storage layer.

    Args:
        raw: Raw JSON-compatible value received from the browser extension.

    Returns:
        The absolute path to the written JSON payload file.
    """

    CACHE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    with RAW_PAYLOAD_PATH.open("w", encoding="utf-8") as file:
        json.dump(raw, file, indent=2, ensure_ascii=False, default=str)

    return RAW_PAYLOAD_PATH


def dump_parsed_product(parsed_product: dict[str, Any]) -> Path:
    """Persist the cleaned product summary used for human SKU verification.

    Args:
        parsed_product: Normalized product dictionary containing title, price,
            main images, and SKU rows.

    Returns:
        The absolute path to the written parsed product JSON file.
    """

    CACHE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    with PARSED_PRODUCT_PATH.open("w", encoding="utf-8") as file:
        json.dump(parsed_product, file, indent=2, ensure_ascii=False, default=str)

    return PARSED_PRODUCT_PATH


def safe_get(data: Any, path: list[str]) -> Any:
    """Read a nested dictionary path without raising key or type errors.

    Args:
        data: Candidate dictionary-like value to inspect.
        path: Sequence of dictionary keys to follow.

    Returns:
        The nested value when every path segment exists, otherwise ``None``.
    """

    current = data

    for key in path:
        if not isinstance(current, dict):
            return None

        current = current.get(key)

    return current


def safe_get_any(data: Any, paths: list[list[str]]) -> Any:
    """Return the first non-empty value from a list of nested dictionary paths.

    Args:
        data: Candidate dictionary-like value to inspect.
        paths: Ordered nested paths to try.

    Returns:
        The first non-empty nested value, otherwise ``None``.
    """

    for path in paths:
        value = safe_get(data, path)
        if value not in (None, "", [], {}):
            return value

    return None


def find_values_by_key(data: Any, target_key: str) -> list[Any]:
    """Recursively collect all values whose dictionary key matches ``target_key``.

    Args:
        data: Raw product payload or nested child value.
        target_key: Exact key name to search for.

    Returns:
        A list of matching values in depth-first traversal order.
    """

    matches: list[Any] = []

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == target_key:
                    matches.append(value)
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(data)
    return matches


def find_first_by_keys(data: Any, keys: list[str]) -> Any:
    """Recursively return the first non-empty value for any key in ``keys``.

    Args:
        data: Raw product payload or nested child value.
        keys: Candidate key names ordered from most to least specific.

    Returns:
        The first discovered non-empty value, otherwise ``None``.
    """

    key_set = set(keys)

    def walk(node: Any) -> Any:
        if isinstance(node, dict):
            for key in keys:
                value = node.get(key)
                if value not in (None, "", [], {}):
                    return value

            for key, value in node.items():
                if key in key_set:
                    continue

                found = walk(value)
                if found not in (None, "", [], {}):
                    return found
        elif isinstance(node, list):
            for item in node:
                found = walk(item)
                if found not in (None, "", [], {}):
                    return found

        return None

    return walk(data)


def normalize_title(value: Any) -> str | None:
    """Normalize a candidate title value into a readable string.

    Args:
        value: Candidate title-like value discovered in the raw payload.

    Returns:
        A stripped title string when available, otherwise ``None``.
    """

    if isinstance(value, str):
        title = value.strip()
        return title or None

    return None


def normalize_price(value: Any) -> str | int | float | None:
    """Normalize a candidate price value into a compact scalar response value.

    Args:
        value: Candidate price-like value discovered in the raw payload.

    Returns:
        A string or numeric price when available, otherwise ``None``.
    """

    if isinstance(value, (int, float)):
        return value

    if isinstance(value, str):
        price = value.strip()
        return price or None

    if isinstance(value, list):
        for item in value:
            normalized = normalize_price(item)
            if normalized is not None:
                return normalized

    if isinstance(value, dict):
        for key in [
            "priceDisplay",
            "offerPriceDisplay",
            "refPrice",
            "price",
            "priceText",
            "value",
            "minPrice",
            "offerMinPrice",
            "maxPrice",
            "offerMaxPrice",
        ]:
            normalized = normalize_price(value.get(key))
            if normalized is not None:
                return normalized

    return None


def collect_image_urls(value: Any) -> list[str]:
    """Extract image URLs from strings, lists, and dictionary-shaped image nodes.

    Args:
        value: Candidate image container from the raw 1688 payload.

    Returns:
        A de-duplicated list of image URLs preserving discovery order.
    """

    images: list[str] = []
    seen: set[str] = set()
    image_keys = {
        "url",
        "imgUrl",
        "imageUrl",
        "imageURL",
        "picUrl",
        "picURL",
        "originalUrl",
        "originalURL",
        "original",
        "bigImageUrl",
        "bigImageURL",
        "originalImageURI",
        "originalImageUri",
        "summImageUrl",
        "summImageURL",
        "fullPathImageURI",
        "imageURI",
        "imageUri",
        "mainImage",
        "mainImageUrl",
    }

    def add(candidate: str) -> None:
        url = candidate.strip()

        if url.startswith("//"):
            url = f"https:{url}"

        if url.startswith("img/") or url.startswith("bao/uploaded/"):
            url = f"https://cbu01.alicdn.com/{url}"

        if not url.startswith(("http://", "https://")):
            return

        if url not in seen:
            seen.add(url)
            images.append(url)

    def walk(node: Any) -> None:
        if isinstance(node, str):
            add(node)
        elif isinstance(node, list):
            for item in node:
                walk(item)
        elif isinstance(node, dict):
            for key in image_keys:
                value = node.get(key)
                if isinstance(value, str):
                    add(value)

            for value in node.values():
                if isinstance(value, (dict, list)):
                    walk(value)

    walk(value)
    return images


def normalize_spec_name(value: Any) -> str:
    """Normalize SKU specification text for the parsed product cache.

    Args:
        value: Raw specification value from SKU maps, often HTML-escaped by 1688.

    Returns:
        A readable specification string, or an empty string when unavailable.
    """

    if value is None:
        return ""

    return unescape(str(value)).strip()


def normalize_stock(value: Any) -> str:
    """Normalize SKU stock-like values into a display-friendly string.

    Args:
        value: Raw stock value such as ``canBookCount`` or ``stock``.

    Returns:
        A string representation for the parsed SKU cache.
    """

    if value is None:
        return ""

    return str(value).strip()


def get_first_sku_value(sku: dict[str, Any], keys: list[str]) -> Any:
    """Read the first non-empty SKU value from a list of candidate keys.

    Args:
        sku: Raw SKU dictionary.
        keys: Ordered candidate key names.

    Returns:
        The first non-empty SKU field value, otherwise ``None``.
    """

    for key in keys:
        value = sku.get(key)
        if value not in (None, "", [], {}):
            return value

    return None


def normalize_sku_row(spec_key: str, sku: dict[str, Any]) -> dict[str, str]:
    """Convert a raw 1688 SKU dictionary into the compact cache row shape.

    Args:
        spec_key: Fallback specification name from map-style SKU containers.
        sku: Raw SKU record containing price, stock, and optional image fields.

    Returns:
        A normalized SKU row with ``spec_name``, ``price``, ``stock``, and
        ``sku_image`` fields.
    """

    spec_name = normalize_spec_name(
        get_first_sku_value(sku, ["specAttrs", "specName", "name", "title"]) or spec_key
    )
    price = normalize_price(
        get_first_sku_value(sku, ["discountPrice", "promotionPrice", "price", "retailPrice"])
    )
    stock = normalize_stock(
        get_first_sku_value(
            sku,
            ["canBookCount", "stock", "stockCount", "inventory", "quantity", "amount"],
        )
    )
    sku_images = collect_image_urls(
        get_first_sku_value(
            sku,
            [
                "skuImage",
                "skuImageUrl",
                "image",
                "imageUrl",
                "picUrl",
                "fullPathImageURI",
                "originalImageURI",
            ],
        )
    )

    return {
        "spec_name": spec_name,
        "price": "" if price is None else str(price),
        "stock": stock,
        "sku_image": sku_images[0] if sku_images else "",
    }


def normalize_sku_container(value: Any) -> list[dict[str, str]]:
    """Normalize a SKU map or list from 1688 into compact parsed rows.

    Args:
        value: Candidate SKU container, either a dict keyed by spec name or a
            list of SKU dictionaries.

    Returns:
        A list of cleaned SKU rows.
    """

    rows: list[dict[str, str]] = []
    seen: set[tuple[str, str, str]] = set()

    def add_row(spec_key: str, sku: Any) -> None:
        if not isinstance(sku, dict):
            return

        row = normalize_sku_row(spec_key, sku)
        identity = (row["spec_name"], row["price"], row["stock"])

        if not row["spec_name"] or identity in seen:
            return

        seen.add(identity)
        rows.append(row)

    if isinstance(value, dict):
        for spec_key, sku in value.items():
            add_row(str(spec_key), sku)
    elif isinstance(value, list):
        for sku in value:
            add_row("", sku)

    return rows


def extract_sku_list(raw_data: dict[str, Any]) -> list[dict[str, str]]:
    """Extract a human-checkable SKU list from known 1688 SKU containers.

    Args:
        raw_data: Raw JSON-compatible dictionary received from the extension.

    Returns:
        A normalized list of SKU rows suitable for ``parsed_product.json``.
    """

    sku_paths = [
        ["result", "data", "Root", "fields", "dataJson", "skuModel", "skuInfoMap"],
        ["result", "data", "Root", "fields", "dataJson", "skuModel", "skuInfoMapOriginal"],
        ["result", "global", "globalData", "model", "tradeModel", "skuMap"],
        [
            "result",
            "global",
            "globalData",
            "model",
            "tradeModel",
            "tradeWithoutPromotion",
            "skuMapOriginal",
        ],
        [
            "result",
            "data",
            "mainPrice",
            "fields",
            "finalPriceModel",
            "tradeWithoutPromotion",
            "skuMapOriginal",
        ],
        ["skuModel", "skuInfoMap"],
        ["skuInfoMap"],
        ["skuMap"],
    ]

    for path in sku_paths:
        rows = normalize_sku_container(safe_get(raw_data, path))
        if rows:
            return rows

    for key in ["skuInfoMap", "skuMap", "skuMapOriginal", "skuInfoMapOriginal"]:
        rows = normalize_sku_container(find_first_by_keys(raw_data, [key]))
        if rows:
            return rows

    return []


def build_parsed_product(raw_data: Any, parsed: dict[str, Any]) -> dict[str, Any]:
    """Build the compact product JSON saved beside the raw capture.

    Args:
        raw_data: Raw JSON-compatible payload received from the extension.
        parsed: Parsed title, image, and price values from ``parse_raw_product``.

    Returns:
        A normalized dictionary matching ``parsed_product.json`` requirements.
    """

    sku_list = extract_sku_list(raw_data) if isinstance(raw_data, dict) else []

    return {
        "title": parsed.get("title") or "",
        "base_price": "" if parsed.get("price") is None else str(parsed.get("price")),
        "main_images": parsed.get("images") or [],
        "sku_list": sku_list,
    }


async def optimize_product_for_export(parsed_product: dict[str, Any]) -> tuple[dict[str, Any], bool]:
    """Best-effort Kiro Agent optimization used by the one-click collect flow.

    The capture workflow must remain useful even when the LLM provider is not
    configured, times out, or returns invalid JSON. This helper therefore tries
    to create an optimized product package, logs any failure, and falls back to
    the cleaned parsed product so ZIP export can still complete.

    Args:
        parsed_product: Cleaned product dictionary from the 1688 parser.

    Returns:
        A tuple of ``(product_for_export, optimized)``. ``optimized`` is true
        only when the Agent returned valid copy and the optimized cache was
        written successfully.
    """

    try:
        optimized_product = await optimize_parsed_product(parsed_product)
        logger.info("Kiro Agent copy generated for export.")
        return optimized_product, True
    except Exception as exc:
        logger.warning(
            "Kiro Agent optimization skipped; exporting parsed product instead: %s",
            exc,
        )
        return parsed_product, False


def extract_1688_data(raw_data: dict[str, Any]) -> dict[str, Any]:
    """Extract core product fields from volatile 1688 payload structures.

    The 1688 detail page can expose product data through different globals such
    as ``FE_GLOBALS``, direct ``globalData`` objects, or newer ``lofty``-shaped
    containers. This parser first tries high-confidence paths, then falls back to
    recursive key sniffing so small layout changes do not break the MVP pipeline.

    Args:
        raw_data: Raw JSON-compatible dictionary received from the extension.

    Returns:
        A dictionary with normalized ``title``, ``images``, and ``price`` values.
    """

    title_paths = [
        ["result", "data", "productTitle", "fields", "title"],
        ["result", "global", "globalData", "model", "offerDetail", "subject"],
        ["result", "data", "Root", "fields", "dataJson", "tempModel", "offerName"],
        ["globalData", "tempModel", "offerName"],
        ["globalData", "offerName"],
        ["offerDomain", "subject"],
        ["offerDomain", "offerName"],
        ["data", "offer", "title"],
        ["data", "offer", "subject"],
        ["lofty", "offer", "title"],
        ["lofty", "offer", "subject"],
        ["offer", "title"],
        ["offer", "subject"],
        ["FE_GLOBALS", "globalData", "tempModel", "offerName"],
        ["FE_GLOBALS", "offerDomain", "subject"],
    ]
    image_paths = [
        ["result", "data", "Root", "fields", "dataJson", "images"],
        ["result", "global", "globalData", "model", "offerDetail", "imageList"],
        ["result", "global", "globalData", "model", "offerDetail", "mainImageList"],
        ["globalData", "images"],
        ["globalData", "imageList"],
        ["globalData", "mainImages"],
        ["offerDomain", "crossBorderImages"],
        ["offerDomain", "picUrls"],
        ["data", "offer", "images"],
        ["data", "offer", "picUrls"],
        ["lofty", "images"],
        ["lofty", "offer", "images"],
        ["lofty", "offer", "picUrls"],
        ["offer", "images"],
        ["offer", "picUrls"],
        ["FE_GLOBALS", "globalData", "images"],
        ["FE_GLOBALS", "offerDomain", "crossBorderImages"],
        ["FE_GLOBALS", "offerDomain", "picUrls"],
    ]
    price_paths = [
        ["result", "global", "globalData", "model", "tradeModel", "priceDisplay"],
        ["result", "global", "globalData", "model", "tradeModel", "minPrice"],
        ["result", "data", "mainPrice", "fields", "priceModel", "currentPrices"],
        [
            "result",
            "data",
            "mainPrice",
            "fields",
            "finalPriceModel",
            "tradeWithoutPromotion",
            "offerPriceDisplay",
        ],
        ["globalData", "refPrice"],
        ["globalData", "price"],
        ["offerDomain", "tradeModel", "offerPriceRanges"],
        ["offerDomain", "price"],
        ["data", "offer", "price"],
        ["lofty", "offer", "price"],
        ["offer", "price"],
        ["FE_GLOBALS", "globalData", "refPrice"],
        ["FE_GLOBALS", "offerDomain", "price"],
    ]

    title = normalize_title(safe_get_any(raw_data, title_paths))
    if not title:
        title = normalize_title(
            find_first_by_keys(raw_data, ["offerName", "subject", "productTitle", "title", "name"])
        )

    image_candidates = [safe_get(raw_data, path) for path in image_paths]
    images: list[str] = []
    seen_images: set[str] = set()
    for value in image_candidates:
        for image_url in collect_image_urls(value):
            if image_url not in seen_images:
                seen_images.add(image_url)
                images.append(image_url)

    if not images:
        recursive_images = find_first_by_keys(
            raw_data,
            [
                "crossBorderImages",
                "picUrls",
                "images",
                "imageList",
                "mainImages",
                "originalImageURI",
                "originalImageUrl",
            ],
        )
        images = collect_image_urls(recursive_images)

    price = normalize_price(safe_get_any(raw_data, price_paths))
    if price is None:
        price = normalize_price(
            find_first_by_keys(raw_data, ["refPrice", "price", "priceText", "offerPriceRanges"])
        )

    return {
        "title": title,
        "images": images,
        "price": price,
    }


def parse_raw_product(raw: Any) -> dict[str, Any]:
    """Parse title, images, and reference price from a deep 1688 payload.

    The parser first checks known 1688 paths, then falls back to recursive key
    searches so captured globals such as ``FE_GLOBALS`` can still produce useful
    MVP fields while we continue mapping the exact page shape.

    Args:
        raw: Raw JSON-compatible product payload received from the extension.

    Returns:
        A dictionary containing ``title``, ``images``, and ``price`` keys.
    """

    if isinstance(raw, dict):
        extracted = extract_1688_data(raw)
        if extracted["title"] or extracted["images"] or extracted["price"] is not None:
            return extracted

    global_data_nodes = find_values_by_key(raw, "globalData")
    offer_domain_nodes = find_values_by_key(raw, "offerDomain")
    temp_model_nodes = find_values_by_key(raw, "tempModel")
    data_nodes = find_values_by_key(raw, "data")

    if isinstance(raw, dict):
        global_data_nodes.insert(0, raw.get("globalData"))
        offer_domain_nodes.insert(0, raw.get("offerDomain"))
        temp_model_nodes.insert(0, raw.get("tempModel"))
        data_nodes.insert(0, raw.get("data"))

    title_candidates: list[Any] = []
    image_candidates: list[Any] = []
    price_candidates: list[Any] = []

    title_candidates.extend(
        [
            safe_get_any(
                raw,
                [
                    ["FE_GLOBALS", "globalData", "tempModel", "offerName"],
                    ["FE_GLOBALS", "globalData", "offerName"],
                    ["FE_GLOBALS", "offerDomain", "subject"],
                    ["data", "globalData", "tempModel", "offerName"],
                    ["data", "offerDomain", "subject"],
                    ["globalData", "tempModel", "offerName"],
                    ["offerDomain", "subject"],
                ],
            )
        ]
    )
    image_candidates.extend(
        [
            safe_get_any(
                raw,
                [
                    ["FE_GLOBALS", "globalData", "images"],
                    ["FE_GLOBALS", "globalData", "imageList"],
                    ["FE_GLOBALS", "globalData", "mainImages"],
                    ["FE_GLOBALS", "offerDomain", "crossBorderImages"],
                    ["FE_GLOBALS", "offerDomain", "picUrls"],
                    ["data", "globalData", "images"],
                    ["data", "offerDomain", "crossBorderImages"],
                    ["globalData", "images"],
                    ["offerDomain", "crossBorderImages"],
                    ["offerDomain", "picUrls"],
                ],
            )
        ]
    )
    price_candidates.extend(
        [
            safe_get_any(
                raw,
                [
                    ["FE_GLOBALS", "globalData", "refPrice"],
                    ["FE_GLOBALS", "globalData", "price"],
                    ["FE_GLOBALS", "offerDomain", "refPrice"],
                    ["data", "globalData", "refPrice"],
                    ["globalData", "refPrice"],
                ],
            )
        ]
    )

    for node in global_data_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["tempModel", "offerName"]),
                safe_get(node, ["tempModel", "subject"]),
                safe_get(node, ["tempModel", "title"]),
                safe_get(node, ["offerName"]),
                safe_get(node, ["subject"]),
                safe_get(node, ["title"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["picUrls"]),
                safe_get(node, ["mainImages"]),
                safe_get(node, ["detailImages"]),
                safe_get(node, ["productImages"]),
            ]
        )
        price_candidates.extend(
            [
                safe_get(node, ["refPrice"]),
                safe_get(node, ["price"]),
                safe_get(node, ["priceInfo"]),
            ]
        )

    for node in offer_domain_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["subject"]),
                safe_get(node, ["offerName"]),
                safe_get(node, ["title"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["crossBorderImages"]),
                safe_get(node, ["picUrls"]),
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["mainImages"]),
            ]
        )
        price_candidates.extend(
            [
                safe_get(node, ["refPrice"]),
                safe_get(node, ["price"]),
            ]
        )

    for node in temp_model_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["offerName"]),
                safe_get(node, ["subject"]),
                safe_get(node, ["title"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["picUrls"]),
            ]
        )

    for node in data_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["tempModel", "offerName"]),
                safe_get(node, ["offerName"]),
                safe_get(node, ["subject"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["picUrls"]),
                safe_get(node, ["crossBorderImages"]),
            ]
        )
        price_candidates.extend(
            [
                safe_get(node, ["refPrice"]),
                safe_get(node, ["price"]),
                safe_get(node, ["priceInfo"]),
            ]
        )

    title = next(
        (normalized for value in title_candidates if (normalized := normalize_title(value))),
        None,
    )
    if not title:
        title = normalize_title(
            find_first_by_keys(raw, ["offerName", "subject", "productTitle", "title", "name"])
        )

    images: list[str] = []
    seen_images: set[str] = set()
    for value in image_candidates:
        for image_url in collect_image_urls(value):
            if image_url not in seen_images:
                seen_images.add(image_url)
                images.append(image_url)

    if not images:
        recursive_images = find_first_by_keys(
            raw,
            [
                "crossBorderImages",
                "picUrls",
                "images",
                "imageList",
                "mainImages",
                "detailImages",
                "productImages",
            ],
        )
        images = collect_image_urls(recursive_images)

    price = next(
        (normalized for value in price_candidates if (normalized := normalize_price(value)) is not None),
        None,
    )
    if price is None:
        price = normalize_price(find_first_by_keys(raw, ["refPrice", "price", "priceText"]))

    return {
        "title": title,
        "images": images,
        "price": price,
    }


def create_app() -> FastAPI:
    """Create and configure the EasyCollect FastAPI application.

    The MVP backend keeps the architecture intentionally light. It mounts the
    local ``app/static`` directory at ``/static`` so cached product images can be
    previewed directly from FastAPI, enables CORS for Vite and Chrome extension
    origins during development, and registers minimal health and collection
    endpoints for the first browser-extension integration test.

    Returns:
        A configured ``FastAPI`` application instance ready for Uvicorn.
    """

    STATIC_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(level=logging.INFO)

    app = FastAPI(
        title="EasyCollect API",
        description="EasyCollect backend data hub and Agent engine",
        version="0.1.0",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=[
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ],
        allow_origin_regex=r"chrome-extension://.*",
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
    app.include_router(export_router)
    app.include_router(optimize_router)

    @app.get("/health", response_model=HealthResponse)
    async def health_check() -> HealthResponse:
        """Return the current API service health state.

        The browser extension and local development tools can call this endpoint
        before posting collected product data. It also verifies that the
        application has created and mounted the local static-media directory.

        Returns:
            A ``HealthResponse`` object containing service and static path info.
        """

        return HealthResponse(
            status="ok",
            service="easycollect-server",
            static_url="/static",
        )

    @app.post("/api/collect", response_model=CollectResponse)
    async def collect_product(
        payload: CollectRequest,
        background_tasks: BackgroundTasks,
    ) -> CollectResponse:
        """Accept raw product detail data captured from a marketplace page.

        During Stage 3 this endpoint persists the latest raw payload for local
        structure inspection, parses common 1688 product fields from deep globals
        such as ``FE_GLOBALS``, and returns the parsed MVP fields to the browser
        extension for end-to-end validation.

        Args:
            payload: Pydantic-validated raw capture payload sent by the extension
                service worker.

        Returns:
            A ``CollectResponse`` confirming that the payload reached the backend.
        """

        raw_file = dump_raw_payload(payload.raw)
        parsed = parse_raw_product(payload.raw)

        title = parsed["title"] or payload.title
        images = parsed["images"] or payload.images
        price = parsed["price"]
        parsed_product = build_parsed_product(
            payload.raw,
            {
                "title": title,
                "images": images,
                "price": price,
            },
        )
        parsed_file = dump_parsed_product(parsed_product)
        if payload.ai_mode:
            product_for_export, optimized = await optimize_product_for_export(parsed_product)
        else:
            product_for_export, optimized = parsed_product, False

        export_package = await build_export_package(product_for_export, optimized=optimized)
        background_tasks.add_task(cleanup_export_later, [export_package.zip_path])

        logger.info("Received EasyCollect payload from %s", payload.source)
        logger.info("URL: %s", payload.url)
        logger.info("Data key: %s", payload.dataKey or "unknown")
        logger.info("AI mode: %s", payload.ai_mode)
        logger.info("Raw payload saved: %s", raw_file)
        logger.info("Parsed product saved: %s", parsed_file)
        logger.info("Agent optimized export: %s", optimized)
        logger.info("Export package URL: %s", export_package.download_url)
        logger.info("Title: %s", title or "not found")
        logger.info("Price: %s", price or "not found")
        logger.info("Images: %s", images[:10])
        logger.info("Image count: %s", len(images))
        logger.info("SKU count: %s", len(parsed_product["sku_list"]))

        return CollectResponse(
            status="success",
            msg="数据接收成功",
            title=title,
            images=images,
            price=price,
            raw_file=str(raw_file),
            parsed_file=str(parsed_file),
            download_url=export_package.download_url,
            optimized=optimized,
        )

    return app


app = create_app()
