import json
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any
from html import unescape

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from app import product_store
from app.api.export import router as export_router
from app.api.optimize import optimize_parsed_product, router as optimize_router
from app.api.shopee import router as shopee_router


BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"
CACHE_DATA_DIR = BASE_DIR / "static" / "cache_data"
RAW_PAYLOAD_PATH = CACHE_DATA_DIR / "raw_payload.json"
PARSED_PRODUCT_PATH = CACHE_DATA_DIR / "parsed_product.json"
logger = logging.getLogger("easycollect")
SHOPEE_IMAGE_BASE_URL = "https://cf.shopee.com.my/file/"


class HealthResponse(BaseModel):
    """Describe the health-check response returned by the API.

    Attributes:
        status: Lightweight service status string. The MVP returns ``ok`` when the
            FastAPI application has started correctly.
        service: Stable service identifier used by the browser extension and
            local debugging scripts.
        static_url: Public URL prefix for locally cached preview media mounted by
            FastAPI's ``StaticFiles`` integration.
    """

    status: str
    service: str
    static_url: str


class CollectRequest(BaseModel):
    """Represent raw product data captured by the browser extension.

    Attributes:
        source: Source marketplace identifier, such as ``1688``.
        url: Product detail page URL where the raw payload was captured.
        capturedAt: ISO timestamp generated by the content script.
        dataKey: Matched page data variable name, such as ``__INITIAL_DATA__`` or
            ``__pageData__``.
        title: Best-effort product title extracted by the content script.
        images: Best-effort product image URLs extracted by the content script.
        platform: Platform detected by the extension, such as ``1688`` or
            ``shopee``.
        ai_mode: Whether Kiro Agent copy optimization should run before export.
        raw: Raw frontend JSON object collected from the product page. The Agent
            workflow will reduce and normalize this payload in later steps.
    """

    source: str
    url: str
    capturedAt: str
    dataKey: str | None = None
    platform: str | None = None
    title: str | None = None
    images: list[str] = Field(default_factory=list)
    ai_mode: bool = False
    raw: Any


class CollectResponse(BaseModel):
    """Describe the acknowledgement returned after receiving product data.

    Attributes:
        status: Indicates whether the backend accepted the captured payload.
        msg: Human-readable result summary for development feedback.
        title: Parsed product title from the raw 1688 payload.
        images: Parsed product image URLs from the raw 1688 payload.
        price: Parsed product reference price from the raw 1688 payload.
        raw_file: Local debug JSON file path where the latest raw payload is saved.
        parsed_file: Local debug JSON file path for the cleaned product summary.
        product_id: Product-library id for the saved inbox item.
        optimized: Whether Kiro Agent copy was applied before saving.
    """

    status: str
    msg: str
    message: str | None = None
    title: str | None = None
    images: list[str] = Field(default_factory=list)
    price: str | int | float | None = None
    product_id: str | None = None
    raw_file: str | None = None
    parsed_file: str | None = None
    download_url: str | None = None
    optimized: bool = False


class ProductSummaryResponse(BaseModel):
    """Return the local EasyCollect product-library list for the dashboard."""

    products: list[dict[str, Any]]


class BulkProductDeleteRequest(BaseModel):
    """Delete multiple product-library rows by id."""

    product_ids: list[str] = Field(default_factory=list)


def dump_raw_payload(raw: Any) -> Path:
    """Persist the latest raw 1688 payload to a local JSON debug file.

    The file is intentionally overwritten on each capture during the MVP phase so
    developers can inspect the most recent real-world payload shape without
    introducing a database or long-term storage layer.

    Args:
        raw: Raw JSON-compatible value received from the browser extension.

    Returns:
        The absolute path to the written JSON payload file.
    """

    CACHE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    with RAW_PAYLOAD_PATH.open("w", encoding="utf-8") as file:
        json.dump(raw, file, indent=2, ensure_ascii=False, default=str)

    return RAW_PAYLOAD_PATH


def dump_parsed_product(parsed_product: dict[str, Any]) -> Path:
    """Persist the cleaned product summary used for human SKU verification.

    Args:
        parsed_product: Normalized product dictionary containing title, price,
            main images, and SKU rows.

    Returns:
        The absolute path to the written parsed product JSON file.
    """

    CACHE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    with PARSED_PRODUCT_PATH.open("w", encoding="utf-8") as file:
        json.dump(parsed_product, file, indent=2, ensure_ascii=False, default=str)

    return PARSED_PRODUCT_PATH


def infer_product_platform(product: dict[str, Any], source_file: str) -> str:
    """Infer a product platform label from cached product content."""

    explicit = product.get("platform")
    if isinstance(explicit, str) and explicit.strip():
        platform = explicit.strip().lower()
        if "shopee" in platform:
            return "Shopee"
        if "1688" in platform:
            return "1688"

    image_blob = json.dumps(product.get("main_images", []), ensure_ascii=False)
    if "shopee" in image_blob or "cf.shopee" in image_blob:
        return "Shopee"
    if "alicdn" in image_blob or "1688" in source_file:
        return "1688"

    return "Unknown"


def product_cache_to_summary(cache_path: Path) -> dict[str, Any] | None:
    """Convert a local product JSON cache file into dashboard row data."""

    if not cache_path.exists():
        return None

    try:
        with cache_path.open("r", encoding="utf-8") as file:
            product = json.load(file)
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Failed to read product cache %s: %s", cache_path, exc)
        return None

    if not isinstance(product, dict):
        return None

    title = (
        product.get("title_optimized")
        or product.get("title")
        or product.get("source_title")
        or "Untitled Product"
    )
    stat = cache_path.stat()

    return {
        "id": cache_path.stem,
        "title": product.get("title") or title,
        "title_optimized": product.get("title_optimized"),
        "source_title": product.get("source_title"),
        "platform": infer_product_platform(product, cache_path.name),
        "base_price": product.get("base_price") or "",
        "main_images": product.get("main_images") or [],
        "sku_list": product.get("sku_list") or [],
        "marketing_copy": product.get("marketing_copy"),
        "bullet_points": product.get("bullet_points") or [],
        "platform_tags": product.get("platform_tags") or [],
        "source_file": cache_path.name,
        "updated_at": datetime.fromtimestamp(stat.st_mtime).isoformat(timespec="seconds"),
    }


def list_local_product_summaries() -> list[dict[str, Any]]:
    """Read current local product cache files for the dashboard MVP."""

    cache_files = [
        CACHE_DATA_DIR / "optimized_product.json",
        CACHE_DATA_DIR / "parsed_product.json",
    ]
    products: list[dict[str, Any]] = []
    seen_ids: set[str] = set()

    for cache_path in cache_files:
        product = product_cache_to_summary(cache_path)
        if not product or product["id"] in seen_ids:
            continue

        seen_ids.add(product["id"])
        products.append(product)

    return products


def safe_get(data: Any, path: list[str]) -> Any:
    """Read a nested dictionary path without raising key or type errors.

    Args:
        data: Candidate dictionary-like value to inspect.
        path: Sequence of dictionary keys to follow.

    Returns:
        The nested value when every path segment exists, otherwise ``None``.
    """

    current = data

    for key in path:
        if not isinstance(current, dict):
            return None

        current = current.get(key)

    return current


def safe_get_any(data: Any, paths: list[list[str]]) -> Any:
    """Return the first non-empty value from a list of nested dictionary paths.

    Args:
        data: Candidate dictionary-like value to inspect.
        paths: Ordered nested paths to try.

    Returns:
        The first non-empty nested value, otherwise ``None``.
    """

    for path in paths:
        value = safe_get(data, path)
        if value not in (None, "", [], {}):
            return value

    return None


def find_values_by_key(data: Any, target_key: str) -> list[Any]:
    """Recursively collect all values whose dictionary key matches ``target_key``.

    Args:
        data: Raw product payload or nested child value.
        target_key: Exact key name to search for.

    Returns:
        A list of matching values in depth-first traversal order.
    """

    matches: list[Any] = []

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == target_key:
                    matches.append(value)
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(data)
    return matches


def find_first_by_keys(data: Any, keys: list[str]) -> Any:
    """Recursively return the first non-empty value for any key in ``keys``.

    Args:
        data: Raw product payload or nested child value.
        keys: Candidate key names ordered from most to least specific.

    Returns:
        The first discovered non-empty value, otherwise ``None``.
    """

    key_set = set(keys)

    def walk(node: Any) -> Any:
        if isinstance(node, dict):
            for key in keys:
                value = node.get(key)
                if value not in (None, "", [], {}):
                    return value

            for key, value in node.items():
                if key in key_set:
                    continue

                found = walk(value)
                if found not in (None, "", [], {}):
                    return found
        elif isinstance(node, list):
            for item in node:
                found = walk(item)
                if found not in (None, "", [], {}):
                    return found

        return None

    return walk(data)


def normalize_title(value: Any) -> str | None:
    """Normalize a candidate title value into a readable string.

    Args:
        value: Candidate title-like value discovered in the raw payload.

    Returns:
        A stripped title string when available, otherwise ``None``.
    """

    if isinstance(value, str):
        title = value.strip()
        return title or None

    return None


def normalize_price(value: Any) -> str | int | float | None:
    """Normalize a candidate price value into a compact scalar response value.

    Args:
        value: Candidate price-like value discovered in the raw payload.

    Returns:
        A string or numeric price when available, otherwise ``None``.
    """

    if isinstance(value, (int, float)):
        return value

    if isinstance(value, str):
        price = value.strip()
        return price or None

    if isinstance(value, list):
        for item in value:
            normalized = normalize_price(item)
            if normalized is not None:
                return normalized

    if isinstance(value, dict):
        for key in [
            "priceDisplay",
            "offerPriceDisplay",
            "refPrice",
            "price",
            "priceText",
            "value",
            "minPrice",
            "offerMinPrice",
            "maxPrice",
            "offerMaxPrice",
        ]:
            normalized = normalize_price(value.get(key))
            if normalized is not None:
                return normalized

    return None


def normalize_shopee_price(value: Any) -> str | None:
    """Convert Shopee integer price units into a human-readable decimal string.

    Shopee item payloads commonly store prices multiplied by ``100000``. For
    example, ``1639000`` represents ``16.39``.

    Args:
        value: Raw Shopee price value.

    Returns:
        Decimal price string, or ``None`` when unavailable.
    """

    if value in (None, "", [], {}):
        return None

    try:
        number = float(value)
    except (TypeError, ValueError):
        return None

    if number <= 0:
        return None

    if number >= 100000:
        number = number / 100000

    return f"{number:.2f}".rstrip("0").rstrip(".")


def normalize_shopee_price_range(price_min: Any, price_max: Any) -> str | None:
    """Format Shopee min/max price fields as a compact price range string."""

    min_price = normalize_shopee_price(price_min)
    max_price = normalize_shopee_price(price_max)

    if min_price and max_price and min_price != max_price:
        return f"{min_price}-{max_price}"

    return min_price or max_price


def normalize_shopee_dom_price(value: Any) -> str | None:
    """Normalize visible Shopee price text such as ``RM5.40 - RM10.00``."""

    if not isinstance(value, str):
        return None

    prices = [
        parse_standard_price(match.group(0))
        for match in re.finditer(r"\d+(?:[.,]\d+)?", value.replace(",", ""))
    ]
    clean_prices = [price for price in prices if price is not None]
    if not clean_prices:
        return None

    min_price = min(clean_prices)
    max_price = max(clean_prices)
    if min_price == max_price:
        return format_standard_price(min_price)

    return f"{format_standard_price(min_price)}-{format_standard_price(max_price)}"


def extract_shopee_dom_price(raw_data: Any, item: dict[str, Any]) -> str | None:
    """Read Shopee DOM price fallback from wrapped frontend payloads."""

    candidates: list[Any] = [item.get("dom_price"), item.get("display_price")]
    if isinstance(raw_data, dict):
        candidates.extend(
            [
                raw_data.get("dom_price"),
                raw_data.get("display_price"),
                safe_get(raw_data, ["data", "dom_price"]),
                safe_get(raw_data, ["data", "display_price"]),
            ]
        )

    for candidate in candidates:
        price = normalize_shopee_dom_price(candidate)
        if price:
            return price

    return None


def extract_shopee_base_price(item: dict[str, Any]) -> str | None:
    """Extract Shopee product-level price from common single/range fields."""

    for key in [
        "price",
        "price_before_discount",
        "raw_price",
        "current_price",
        "min_price",
        "max_price",
    ]:
        price = normalize_shopee_price(item.get(key))
        if price:
            return price

    range_candidates = [
        ("price_min", "price_max"),
        ("min_price", "max_price"),
        ("price_min_before_discount", "price_max_before_discount"),
    ]
    for min_key, max_key in range_candidates:
        price_range = normalize_shopee_price_range(item.get(min_key), item.get(max_key))
        if price_range:
            return price_range

    price_stocks = item.get("price_stocks")
    if isinstance(price_stocks, list):
        for price_stock in price_stocks:
            if not isinstance(price_stock, dict):
                continue

            price = normalize_shopee_price(
                price_stock.get("price")
                or price_stock.get("current_price")
                or price_stock.get("price_before_discount")
            )
            if price:
                return price

    return None


def parse_standard_price(value: Any) -> float | None:
    """Parse a normalized or raw marketplace price into a comparable float.

    Shopee can expose raw integer prices multiplied by ``100000``. This helper
    accepts already-normalized values such as ``15.90`` and raw values such as
    ``1590000`` so downstream healing can compare prices safely.
    """

    if value in (None, "", [], {}):
        return None

    if isinstance(value, (int, float)):
        number = float(value)
    elif isinstance(value, str):
        cleaned = value.strip().lower()
        if cleaned in {"not found", "none", "null", "nan", "0", "0.0", "0.00"}:
            return None

        match = re.search(r"\d+(?:[.,]\d+)?", cleaned.replace(",", ""))
        if not match:
            return None

        try:
            number = float(match.group(0))
        except ValueError:
            return None
    else:
        return None

    if number <= 0:
        return None

    if number >= 100000:
        number = number / 100000

    return number if number > 0 else None


def format_standard_price(value: float) -> str:
    """Format a marketplace price with two decimal places for cache and CSV."""

    return f"{value:.2f}"


def is_missing_base_price(value: Any) -> bool:
    """Return whether a product-level price needs SKU-based self-healing."""

    if value in (None, "", [], {}):
        return True

    if isinstance(value, str) and value.strip().lower() in {
        "not found",
        "none",
        "null",
        "nan",
        "0",
        "0.0",
        "0.00",
    }:
        return True

    return parse_standard_price(value) is None


def normalize_base_price_value(value: Any) -> str:
    """Normalize a base price or price range without losing range semantics."""

    if isinstance(value, str) and "-" in value:
        parts = [parse_standard_price(part) for part in value.split("-", 1)]
        if parts[0] is not None and parts[1] is not None:
            if parts[0] == parts[1]:
                return format_standard_price(parts[0])
            return f"{format_standard_price(parts[0])}-{format_standard_price(parts[1])}"

    price = parse_standard_price(value)
    return "" if price is None else format_standard_price(price)


def heal_product_prices(clean_data: dict[str, Any]) -> dict[str, Any]:
    """Normalize SKU prices and infer ``base_price`` from SKU rows when needed."""

    sku_list = clean_data.get("sku_list")
    if not isinstance(sku_list, list):
        sku_list = []
        clean_data["sku_list"] = sku_list

    sku_prices: list[float] = []
    for sku in sku_list:
        if not isinstance(sku, dict):
            continue

        price = parse_standard_price(sku.get("price"))
        if price is None:
            sku["price"] = ""
            continue

        sku["price"] = format_standard_price(price)
        sku_prices.append(price)

    base_price = clean_data.get("base_price")
    if is_missing_base_price(base_price) and sku_prices:
        min_price = min(sku_prices)
        max_price = max(sku_prices)
        clean_data["base_price"] = (
            format_standard_price(min_price)
            if min_price == max_price
            else f"{format_standard_price(min_price)}-{format_standard_price(max_price)}"
        )
    else:
        normalized_base_price = normalize_base_price_value(base_price)
        if normalized_base_price:
            clean_data["base_price"] = normalized_base_price

    return clean_data


def infer_price_range_from_skus(sku_list: list[dict[str, Any]]) -> str | None:
    """Infer a product price or price range from normalized SKU row prices."""

    prices = [
        price
        for sku in sku_list
        if isinstance(sku, dict)
        for price in [parse_standard_price(sku.get("price"))]
        if price is not None
    ]
    if not prices:
        return None

    min_price = min(prices)
    max_price = max(prices)
    if min_price == max_price:
        return format_standard_price(min_price)

    return f"{format_standard_price(min_price)}-{format_standard_price(max_price)}"


def normalize_shopee_image(value: Any) -> str | None:
    """Normalize a Shopee image ID or URL into an absolute image URL."""

    if not isinstance(value, str):
        return None

    image = value.strip()
    if not image:
        return None

    if image.startswith("//"):
        return f"https:{image}"

    if image.startswith(("http://", "https://")):
        return image

    return f"{SHOPEE_IMAGE_BASE_URL}{image}"


def collect_image_urls(value: Any) -> list[str]:
    """Extract image URLs from strings, lists, and dictionary-shaped image nodes.

    Args:
        value: Candidate image container from the raw 1688 payload.

    Returns:
        A de-duplicated list of image URLs preserving discovery order.
    """

    images: list[str] = []
    seen: set[str] = set()
    image_keys = {
        "url",
        "imgUrl",
        "imageUrl",
        "imageURL",
        "picUrl",
        "picURL",
        "originalUrl",
        "originalURL",
        "original",
        "bigImageUrl",
        "bigImageURL",
        "originalImageURI",
        "originalImageUri",
        "summImageUrl",
        "summImageURL",
        "fullPathImageURI",
        "imageURI",
        "imageUri",
        "mainImage",
        "mainImageUrl",
    }

    def add(candidate: str) -> None:
        url = candidate.strip()

        if url.startswith("//"):
            url = f"https:{url}"

        if url.startswith("img/") or url.startswith("bao/uploaded/"):
            url = f"https://cbu01.alicdn.com/{url}"

        if not url.startswith(("http://", "https://")):
            return

        if url not in seen:
            seen.add(url)
            images.append(url)

    def walk(node: Any) -> None:
        if isinstance(node, str):
            add(node)
        elif isinstance(node, list):
            for item in node:
                walk(item)
        elif isinstance(node, dict):
            for key in image_keys:
                value = node.get(key)
                if isinstance(value, str):
                    add(value)

            for value in node.values():
                if isinstance(value, (dict, list)):
                    walk(value)

    walk(value)
    return images


def normalize_spec_name(value: Any) -> str:
    """Normalize SKU specification text for the parsed product cache.

    Args:
        value: Raw specification value from SKU maps, often HTML-escaped by 1688.

    Returns:
        A readable specification string, or an empty string when unavailable.
    """

    if value is None:
        return ""

    return unescape(str(value)).strip()


def normalize_lookup_key(value: Any) -> str:
    """Normalize option/spec aliases for fuzzy SKU image lookup."""

    return re.sub(r"\s+", " ", normalize_spec_name(value)).strip().lower()


def normalize_coord_key(value: Any) -> str:
    """Normalize 1688 property-value ids used for index-based SKU mapping."""

    if value in (None, "", [], {}):
        return ""

    return str(value).strip()


def extract_coord_keys(value: Any) -> list[str]:
    """Extract possible 1688 property coordinate ids from strings/lists/dicts."""

    keys: list[str] = []
    seen: set[str] = set()

    def remember(candidate: Any) -> None:
        key = normalize_coord_key(candidate)
        if key and key not in seen:
            seen.add(key)
            keys.append(key)

    def add(candidate: Any) -> None:
        text = normalize_coord_key(candidate)
        if not text:
            return

        remember(text)
        for token in re.split(r"[&;,|>\s]+", text):
            remember(token)
            for separator in [":", "="]:
                if separator in token:
                    right_side = token.rsplit(separator, 1)[-1]
                    remember(right_side)

    if isinstance(value, dict):
        for key in [
            "specId",
            "specID",
            "propId",
            "propID",
            "propIds",
            "propValueId",
            "propValueID",
            "propertyValueId",
            "propertyValueID",
            "skuProps",
            "skuPropIds",
            "valueId",
            "valueID",
            "vid",
            "id",
        ]:
            add(value.get(key))
    elif isinstance(value, list):
        for item in value:
            add(item)
    else:
        add(value)

    return keys


def normalize_stock(value: Any) -> str:
    """Normalize SKU stock-like values into a display-friendly string.

    Args:
        value: Raw stock value such as ``canBookCount`` or ``stock``.

    Returns:
        A string representation for the parsed SKU cache.
    """

    if value is None:
        return ""

    return str(value).strip()


def get_first_sku_value(sku: dict[str, Any], keys: list[str]) -> Any:
    """Read the first non-empty SKU value from a list of candidate keys.

    Args:
        sku: Raw SKU dictionary.
        keys: Ordered candidate key names.

    Returns:
        The first non-empty SKU field value, otherwise ``None``.
    """

    for key in keys:
        value = sku.get(key)
        if value not in (None, "", [], {}):
            return value

    return None


def normalize_sku_row(spec_key: str, sku: dict[str, Any]) -> dict[str, Any]:
    """Convert a raw 1688 SKU dictionary into the compact cache row shape.

    Args:
        spec_key: Fallback specification name from map-style SKU containers.
        sku: Raw SKU record containing price, stock, and optional image fields.

    Returns:
        A normalized SKU row with ``spec_name``, ``price``, ``stock``, and
        ``sku_image`` fields.
    """

    spec_name = normalize_spec_name(
        get_first_sku_value(sku, ["specAttrs", "specName", "name", "title"]) or spec_key
    )
    price = normalize_price(
        get_first_sku_value(sku, ["discountPrice", "promotionPrice", "price", "retailPrice"])
    )
    stock = normalize_stock(
        get_first_sku_value(
            sku,
            ["canBookCount", "stock", "stockCount", "inventory", "quantity", "amount"],
        )
    )
    sku_images = collect_image_urls(
        get_first_sku_value(
            sku,
            [
                "skuImage",
                "skuImageUrl",
                "skuImageURI",
                "skuImageUri",
                "sku_image",
                "sku_image_url",
                "sku_image_uri",
                "image",
                "imageUrl",
                "imageURL",
                "imageURI",
                "imageUri",
                "image_url",
                "image_uri",
                "picUrl",
                "picURL",
                "pic_url",
                "fullPathImageURI",
                "fullPathImageUri",
                "originalImageURI",
                "originalImageUri",
                "originalImageUrl",
            ],
        )
    )

    coord_keys = extract_coord_keys(spec_key)
    coord_keys.extend(
        key
        for key in extract_coord_keys(sku)
        if key not in coord_keys
    )

    return {
        "spec_name": spec_name,
        "price": "" if price is None else str(price),
        "stock": stock,
        "sku_image": sku_images[0] if sku_images else "",
        "_coord_keys": coord_keys,
    }


def normalize_sku_container(value: Any) -> list[dict[str, Any]]:
    """Normalize a SKU map or list from 1688 into compact parsed rows.

    Args:
        value: Candidate SKU container, either a dict keyed by spec name or a
            list of SKU dictionaries.

    Returns:
        A list of cleaned SKU rows.
    """

    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str]] = set()

    def add_row(spec_key: str, sku: Any) -> None:
        if not isinstance(sku, dict):
            return

        row = normalize_sku_row(spec_key, sku)
        identity = (row["spec_name"], row["price"], row["stock"])

        if not row["spec_name"] or identity in seen:
            return

        seen.add(identity)
        rows.append(row)

    if isinstance(value, dict):
        for spec_key, sku in value.items():
            add_row(str(spec_key), sku)
    elif isinstance(value, list):
        for sku in value:
            add_row("", sku)

    return rows


def add_1688_sku_image_aliases(
    image_map: dict[str, str],
    aliases: list[Any],
    image_value: Any,
) -> None:
    """Register SKU option aliases against the first discovered image URL."""

    image_urls = collect_image_urls(image_value)
    if not image_urls:
        return

    image_url = image_urls[0]
    for alias in aliases:
        lookup_key = normalize_lookup_key(alias)
        if lookup_key and lookup_key not in image_map:
            image_map[lookup_key] = image_url

        for coord_key in extract_coord_keys(alias):
            if coord_key and coord_key not in image_map:
                image_map[coord_key] = image_url


def iter_1688_sku_props(raw_data: Any) -> list[Any]:
    """Return likely 1688 ``skuProps`` containers from known payload shapes."""

    sku_props_paths = [
        ["globalData", "skuModel", "skuProps"],
        ["globalData", "model", "skuModel", "skuProps"],
        ["globalData", "model", "tradeModel", "skuProps"],
        ["result", "global", "globalData", "skuModel", "skuProps"],
        ["result", "global", "globalData", "model", "skuModel", "skuProps"],
        ["result", "global", "globalData", "model", "tradeModel", "skuProps"],
        ["result", "data", "Root", "fields", "dataJson", "skuModel", "skuProps"],
        ["result", "data", "Root", "fields", "dataJson", "skuProps"],
        ["skuModel", "skuProps"],
        ["skuProps"],
    ]

    containers: list[Any] = []
    for path in sku_props_paths:
        value = safe_get(raw_data, path)
        if isinstance(value, list):
            containers.append(value)

    for value in find_values_by_key(raw_data, "skuProps"):
        if isinstance(value, list):
            containers.append(value)

    return containers


def build_1688_sku_props_image_map(raw_data: Any) -> dict[str, str]:
    """Build a high-confidence 1688 option-name to image map from ``skuProps``."""

    image_map: dict[str, str] = {}
    alias_keys = [
        "name",
        "value",
        "propValue",
        "propValueName",
        "valueName",
        "specName",
        "specValue",
        "displayName",
        "title",
        "specId",
        "specID",
        "propId",
        "propID",
        "propValueId",
        "propValueID",
        "propertyValueId",
        "propertyValueID",
        "valueId",
        "valueID",
        "vid",
        "id",
    ]
    image_keys = [
        "imageUrl",
        "imageURL",
        "image_url",
        "image",
        "imageURI",
        "imageUri",
        "image_uri",
        "skuImage",
        "skuImageUrl",
        "skuImageURL",
        "skuImageURI",
        "skuImageUri",
        "sku_image",
        "sku_image_url",
        "sku_image_uri",
        "picUrl",
        "picURL",
        "pic_url",
        "fullPathImageURI",
        "fullPathImageUri",
        "full_path_image_uri",
        "originalImageURI",
        "originalImageUri",
        "originalImageUrl",
        "original_image_uri",
        "original_image_url",
    ]

    for sku_props in iter_1688_sku_props(raw_data):
        for prop_index, prop in enumerate(sku_props):
            if not isinstance(prop, dict):
                continue

            prop_aliases = [
                prop.get(key)
                for key in [
                    "fid",
                    "id",
                    "propId",
                    "propID",
                    "propertyId",
                    "propertyID",
                    "name",
                    "propName",
                ]
                if prop.get(key) not in (None, "", [], {})
            ]
            values = (
                prop.get("value")
                or prop.get("values")
                or prop.get("propertyValues")
                or prop.get("propValues")
                or prop.get("optionList")
                or []
            )
            if isinstance(values, dict):
                values = list(values.values())
            if not isinstance(values, list):
                continue

            for option_index, option in enumerate(values):
                if not isinstance(option, dict):
                    continue

                aliases = [
                    option.get(key)
                    for key in alias_keys
                    if option.get(key) not in (None, "", [], {})
                ]
                image_value = next(
                    (
                        option.get(image_key)
                        for image_key in image_keys
                        if option.get(image_key) not in (None, "", [], {})
                    ),
                    None,
                )
                if image_value not in (None, "", [], {}):
                    aliases.extend(
                        [
                            option_index,
                            f"{prop_index}:{option_index}",
                            *[
                                f"{prop_alias}:{option.get(option_key)}"
                                for prop_alias in prop_aliases
                                for option_key in alias_keys
                                if option.get(option_key) not in (None, "", [], {})
                            ],
                        ]
                    )
                    add_1688_sku_image_aliases(image_map, aliases, image_value)

    return image_map


def extract_1688_images_recursively(data: Any, image_map: dict[str, str]) -> None:
    """Recursively sniff 1688 option image pairs from unstable skuModel shapes."""

    name_keys = [
        "name",
        "value",
        "propValue",
        "propValueName",
        "valueName",
        "specName",
        "specValue",
        "displayName",
        "title",
    ]
    id_keys = [
        "specId",
        "specID",
        "propId",
        "propID",
        "propValueId",
        "propValueID",
        "propertyValueId",
        "propertyValueID",
        "valueId",
        "valueID",
        "vid",
        "id",
    ]
    image_keys = [
        "imageUrl",
        "imageURL",
        "image_url",
        "image",
        "imageURI",
        "imageUri",
        "image_uri",
        "skuImage",
        "skuImageUrl",
        "skuImageURL",
        "skuImageURI",
        "skuImageUri",
        "sku_image",
        "sku_image_url",
        "sku_image_uri",
        "picUrl",
        "picURL",
        "pic_url",
        "fullPathImageURI",
        "fullPathImageUri",
        "full_path_image_uri",
        "originalImageURI",
        "originalImageUri",
        "originalImageUrl",
        "original_image_uri",
        "original_image_url",
    ]

    def walk(node: Any, inherited_aliases: list[Any] | None = None) -> None:
        aliases = list(inherited_aliases or [])

        if isinstance(node, dict):
            local_aliases = [
                node.get(key)
                for key in name_keys + id_keys
                if node.get(key) not in (None, "", [], {})
            ]
            aliases.extend(local_aliases)

            image_value = next(
                (
                    node.get(key)
                    for key in image_keys
                    if node.get(key) not in (None, "", [], {})
                ),
                None,
            )
            if image_value not in (None, "", [], {}):
                add_1688_sku_image_aliases(image_map, aliases, image_value)

            for key, value in node.items():
                if isinstance(value, str):
                    urls = collect_image_urls(value)
                    if urls:
                        add_1688_sku_image_aliases(image_map, aliases + [key], value)
                elif isinstance(value, (dict, list)):
                    walk(value, aliases)
        elif isinstance(node, list):
            for index, item in enumerate(node):
                walk(item, aliases + [index])

    walk(data)


def build_1688_sku_image_map(raw_data: Any) -> dict[str, str]:
    """Build a best-effort map from 1688 spec names/specIds to SKU images.

    1688 often keeps variation pictures in ``skuProps`` or image lookup tables
    rather than inside each ``skuMap`` row. This recursive sniffer registers any
    dictionary that contains both image-like fields and option identifiers.
    """

    image_map: dict[str, str] = build_1688_sku_props_image_map(raw_data)
    for sku_model in find_values_by_key(raw_data, "skuModel"):
        extract_1688_images_recursively(sku_model, image_map)
    extract_1688_images_recursively(raw_data, image_map)
    option_name_keys = [
        "name",
        "value",
        "propValue",
        "propValueName",
        "valueName",
        "specName",
        "specAttrs",
        "title",
    ]
    option_id_keys = [
        "specId",
        "specID",
        "propId",
        "propID",
        "propValueId",
        "propValueID",
        "propertyValueId",
        "propertyValueID",
        "valueId",
        "valueID",
        "vid",
        "id",
        "skuId",
        "skuID",
    ]
    image_keys = [
        "image",
        "imageUrl",
        "imageURL",
        "image_url",
        "imageURI",
        "imageUri",
        "image_uri",
        "skuImage",
        "skuImageUrl",
        "skuImageURL",
        "skuImageURI",
        "skuImageUri",
        "sku_image",
        "sku_image_url",
        "sku_image_uri",
        "picUrl",
        "picURL",
        "pic_url",
        "fullPathImageURI",
        "fullPathImageUri",
        "full_path_image_uri",
        "originalImageURI",
        "originalImageUri",
        "originalImageUrl",
        "original_image_uri",
        "original_image_url",
    ]

    def register_dict(node: dict[str, Any]) -> None:
        aliases: list[Any] = []
        for key in option_name_keys + option_id_keys:
            value = node.get(key)
            if value not in (None, "", [], {}):
                aliases.append(value)

        for key in image_keys:
            value = node.get(key)
            if value not in (None, "", [], {}):
                add_1688_sku_image_aliases(image_map, aliases, value)

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            register_dict(node)

            # Map-style image tables are common: {specId: "img/..."}.
            for key, value in node.items():
                if isinstance(value, str):
                    urls = collect_image_urls(value)
                    if urls:
                        add_1688_sku_image_aliases(image_map, [key], value)

            for value in node.values():
                if isinstance(value, (dict, list)):
                    walk(value)
        elif isinstance(node, list):
            for item in node:
                if isinstance(item, (dict, list)):
                    walk(item)

    walk(raw_data)
    return image_map


def find_ordered_1688_sku_images(raw_data: Any, expected_count: int) -> list[str]:
    """Find an ordered 1688 SKU image list for last-resort row assignment.

    Some 1688 pages expose SKU option pictures as a plain ordered image array
    rather than an aliasable ``specId -> image`` map. When alias lookup fails,
    this helper tries high-confidence SKU image containers first, then falls
    back to the product ``images`` array only if it has enough images to cover
    the SKU rows.
    """

    candidate_paths = [
        ["result", "data", "Root", "fields", "dataJson", "skuProps"],
        ["result", "global", "globalData", "model", "skuProps"],
        ["result", "global", "globalData", "skuProps"],
        ["globalData", "skuProps"],
        ["skuProps"],
        ["skuImageMap"],
        ["skuImages"],
        ["skuImageList"],
    ]

    for path in candidate_paths:
        images = collect_image_urls(safe_get(raw_data, path))
        if len(images) >= expected_count:
            return images

    for key in ["skuProps", "skuImageMap", "skuImages", "skuImageList", "skuPropImages"]:
        for value in find_values_by_key(raw_data, key):
            images = collect_image_urls(value)
            if len(images) >= expected_count:
                return images

    return []


def attach_1688_sku_images(
    rows: list[dict[str, Any]],
    raw_data: dict[str, Any],
) -> list[dict[str, str]]:
    """Fill missing 1688 SKU images from real skuProps/spec image maps only."""

    image_map = build_1688_sku_image_map(raw_data)
    if not image_map:
        return rows

    for row in rows:
        if row.get("sku_image"):
            continue

        for coord_key in row.get("_coord_keys", []):
            image_url = image_map.get(normalize_coord_key(coord_key))
            if image_url:
                row["sku_image"] = image_url
                break

        if row.get("sku_image"):
            continue

        spec_name = row.get("spec_name", "")
        lookup_keys = [normalize_lookup_key(spec_name)]
        for part in spec_name.split(">"):
            key = normalize_lookup_key(part)
            if key:
                lookup_keys.append(key)

        for key in lookup_keys:
            image_url = image_map.get(key)
            if image_url:
                row["sku_image"] = image_url
                break

        if row.get("sku_image"):
            continue

        normalized_spec = normalize_lookup_key(spec_name)
        for alias, image_url in image_map.items():
            if alias and (alias in normalized_spec or normalized_spec in alias):
                row["sku_image"] = image_url
                break

    for row in rows:
        row.pop("_coord_keys", None)

    return rows


def extract_sku_list(raw_data: dict[str, Any]) -> list[dict[str, str]]:
    """Extract a human-checkable SKU list from known 1688 SKU containers.

    Args:
        raw_data: Raw JSON-compatible dictionary received from the extension.

    Returns:
        A normalized list of SKU rows suitable for ``parsed_product.json``.
    """

    sku_paths = [
        ["result", "data", "Root", "fields", "dataJson", "skuModel", "skuInfoMap"],
        ["result", "data", "Root", "fields", "dataJson", "skuModel", "skuInfoMapOriginal"],
        ["result", "global", "globalData", "model", "tradeModel", "skuMap"],
        [
            "result",
            "global",
            "globalData",
            "model",
            "tradeModel",
            "tradeWithoutPromotion",
            "skuMapOriginal",
        ],
        [
            "result",
            "data",
            "mainPrice",
            "fields",
            "finalPriceModel",
            "tradeWithoutPromotion",
            "skuMapOriginal",
        ],
        ["skuModel", "skuInfoMap"],
        ["skuInfoMap"],
        ["skuMap"],
    ]

    for path in sku_paths:
        rows = normalize_sku_container(safe_get(raw_data, path))
        if rows:
            return attach_1688_sku_images(rows, raw_data)

    for key in ["skuInfoMap", "skuMap", "skuMapOriginal", "skuInfoMapOriginal"]:
        rows = normalize_sku_container(find_first_by_keys(raw_data, [key]))
        if rows:
            return attach_1688_sku_images(rows, raw_data)

    return []


def score_shopee_item_node(node: dict[str, Any]) -> int:
    """Score whether a dictionary looks like a Shopee item payload."""

    score = 0
    if isinstance(node.get("name"), str):
        score += 40
    if isinstance(node.get("images"), list):
        score += 30
    if isinstance(node.get("tier_variations"), list):
        score += 40
    if isinstance(node.get("models"), list):
        score += 40
    if node.get("itemid") or node.get("item_id"):
        score += 20
    if node.get("price") or node.get("price_min"):
        score += 20
    return score


def find_best_shopee_item(raw_data: Any) -> dict[str, Any]:
    """Find the most likely Shopee item object in a deep raw payload."""

    direct_paths = [
        ["data", "item"],
        ["data", "item_info"],
        ["data", "itemInfo"],
        ["item"],
        ["item_info"],
        ["itemInfo"],
    ]
    for path in direct_paths:
        value = safe_get(raw_data, path)
        if isinstance(value, dict) and score_shopee_item_node(value) > 0:
            return value

    best: dict[str, Any] = {}
    best_score = 0

    def walk(node: Any) -> None:
        nonlocal best, best_score

        if isinstance(node, dict):
            score = score_shopee_item_node(node)
            if score > best_score:
                best = node
                best_score = score

            for value in node.values():
                if isinstance(value, (dict, list)):
                    walk(value)
        elif isinstance(node, list):
            for item in node:
                if isinstance(item, (dict, list)):
                    walk(item)

    walk(raw_data)
    return best


def get_shopee_item_data(raw_data: dict[str, Any]) -> dict[str, Any]:
    """Return Shopee official item data from common API response wrappers."""

    data_node = raw_data.get("data", raw_data)
    if not isinstance(data_node, dict):
        return find_best_shopee_item(raw_data)

    item_node = data_node.get("item", data_node)
    if isinstance(item_node, dict) and score_shopee_item_node(item_node) > 0:
        return item_node

    return find_best_shopee_item(raw_data)


def extract_shopee_images(item: dict[str, Any]) -> list[str]:
    """Extract Shopee main image URLs from item image IDs or URL strings."""

    images: list[str] = []
    seen: set[str] = set()

    def add(raw_image: Any) -> None:
        if isinstance(raw_image, dict):
            raw_image = (
                raw_image.get("image_id")
                or raw_image.get("image")
                or raw_image.get("url")
            )

        image_url = normalize_shopee_image(raw_image)
        if image_url and image_url not in seen:
            seen.add(image_url)
            images.append(image_url)

    raw_images = item.get("images")
    if isinstance(raw_images, list):
        for raw_image in raw_images:
            add(raw_image)

    if images:
        return images

    raw_image_list = item.get("image_list")
    if isinstance(raw_image_list, list):
        for raw_image in raw_image_list:
            add(raw_image)

    if images:
        return images

    add(item.get("image"))

    return images


def find_first_shopee_images_array(raw_data: Any) -> list[str]:
    """Find and normalize the first Shopee ``images`` array in a raw payload."""

    found: list[str] = []

    def walk(node: Any) -> None:
        nonlocal found
        if found:
            return

        if isinstance(node, dict):
            images_value = node.get("images")
            if isinstance(images_value, list) and images_value:
                found = extract_shopee_images({"images": images_value})
                if found:
                    return

            for value in node.values():
                if isinstance(value, (dict, list)):
                    walk(value)
                    if found:
                        return
        elif isinstance(node, list):
            for item in node:
                if isinstance(item, (dict, list)):
                    walk(item)
                    if found:
                        return

    walk(raw_data)
    return found


def get_tier_option_names(tier_variations: list[Any]) -> list[list[str]]:
    """Return Shopee tier option names grouped by variation dimension."""

    option_groups: list[list[str]] = []
    for tier in tier_variations:
        if not isinstance(tier, dict):
            continue

        options = tier.get("options") or tier.get("option_list") or []
        names: list[str] = []
        if isinstance(options, list):
            for option in options:
                if isinstance(option, dict):
                    name = option.get("name") or option.get("option") or option.get("value")
                else:
                    name = option
                names.append(normalize_spec_name(name))
        option_groups.append(names)

    return option_groups


def get_tier_option_images(tier_variations: list[Any]) -> dict[tuple[int, int], str]:
    """Map Shopee tier option indexes to variation image URLs when available."""

    images: dict[tuple[int, int], str] = {}
    for tier_index, tier in enumerate(tier_variations):
        if not isinstance(tier, dict):
            continue

        options = tier.get("options") or tier.get("option_list") or []
        option_images = tier.get("images") or tier.get("image_list") or []

        if isinstance(options, list):
            for option_index, option in enumerate(options):
                raw_image = None
                if isinstance(option, dict):
                    raw_image = (
                        option.get("image_id")
                        or option.get("image")
                        or option.get("image_url")
                        or option.get("imageUrl")
                        or option.get("cover")
                        or option.get("thumbnail")
                    )
                image_url = normalize_shopee_image(raw_image)
                if image_url:
                    images[(tier_index, option_index)] = image_url

        if isinstance(option_images, list):
            for option_index, raw_image in enumerate(option_images):
                if isinstance(raw_image, dict):
                    raw_image = raw_image.get("image_id") or raw_image.get("image")
                image_url = normalize_shopee_image(raw_image)
                if image_url:
                    images[(tier_index, option_index)] = image_url

    return images


def get_shopee_tier_indexes(model: dict[str, Any]) -> list[int]:
    """Read Shopee model tier indexes from common payload locations."""

    extinfo = model.get("extinfo")
    tier_indexes = extinfo.get("tier_index") if isinstance(extinfo, dict) else None
    if not isinstance(tier_indexes, list):
        tier_indexes = model.get("tier_index")
    if not isinstance(tier_indexes, list):
        tier_indexes = model.get("tier_indexes")
    if not isinstance(tier_indexes, list):
        return []

    return [index for index in tier_indexes if isinstance(index, int)]


def get_tier_option_image_aliases(tier_variations: list[Any]) -> dict[str, str]:
    """Map Shopee option names such as ``Black`` to their variation image."""

    aliases: dict[str, str] = {}
    option_groups = get_tier_option_names(tier_variations)
    option_images = get_tier_option_images(tier_variations)

    for (tier_index, option_index), image_url in option_images.items():
        if tier_index >= len(option_groups):
            continue
        options = option_groups[tier_index]
        if not (0 <= option_index < len(options)):
            continue

        option_name = options[option_index]
        key = normalize_lookup_key(option_name)
        if key:
            aliases[key] = image_url

    return aliases


def build_shopee_model_spec(
    model: dict[str, Any],
    option_groups: list[list[str]],
) -> str:
    """Build a readable Shopee SKU spec name from model tier indexes."""

    direct_name = normalize_spec_name(model.get("name") or model.get("model_name"))
    if direct_name:
        return direct_name

    tier_indexes = get_shopee_tier_indexes(model)
    if not tier_indexes:
        return direct_name

    parts: list[str] = []
    for group_index, option_index in enumerate(tier_indexes):
        if not isinstance(option_index, int):
            continue
        if group_index >= len(option_groups):
            continue
        options = option_groups[group_index]
        if 0 <= option_index < len(options) and options[option_index]:
            parts.append(options[option_index])

    return " > ".join(parts) or direct_name


def build_shopee_model_image(
    model: dict[str, Any],
    option_images: dict[tuple[int, int], str],
    image_aliases: dict[str, str],
    spec_name: str,
) -> str:
    """Resolve a Shopee variation image from model fields or tier option images."""

    for key in [
        "image",
        "image_id",
        "image_url",
        "model_image",
        "model_image_id",
        "cover",
        "cover_image",
        "thumb",
        "thumbnail",
    ]:
        image_url = normalize_shopee_image(model.get(key))
        if image_url:
            return image_url

    for group_index, option_index in enumerate(get_shopee_tier_indexes(model)):
        image_url = option_images.get((group_index, option_index))
        if image_url:
            return image_url

    spec_parts = [
        normalize_lookup_key(part)
        for part in re.split(r"\s*>\s*|[;；|/，,、]+", spec_name)
        if normalize_lookup_key(part)
    ]
    for part in spec_parts:
        image_url = image_aliases.get(part)
        if image_url:
            return image_url

    normalized_spec = normalize_lookup_key(spec_name)
    for alias, image_url in image_aliases.items():
        if alias and alias in normalized_spec:
            return image_url

    return ""


def fill_shopee_sku_image_fallbacks(
    sku_list: list[dict[str, str]],
    main_images: list[str],
) -> list[dict[str, str]]:
    """Ensure Shopee SKU rows always have an image when a main image exists."""

    if not main_images:
        return sku_list

    fallback_image = main_images[0]
    for sku in sku_list:
        if isinstance(sku, dict) and not sku.get("sku_image"):
            sku["sku_image"] = fallback_image

    return sku_list


def shopee_sku_identity(model: dict[str, Any], spec_name: str) -> str:
    """Return a stable dedupe key for one Shopee model row."""

    for key in ["modelid", "model_id", "id", "sku_id", "skuId"]:
        value = model.get(key)
        if value not in (None, "", [], {}):
            return f"id:{value}"

    tier_indexes = get_shopee_tier_indexes(model)
    if tier_indexes:
        return "tier:" + "_".join(str(index) for index in tier_indexes)

    return "spec:" + normalize_lookup_key(spec_name)


def dedupe_sku_rows(sku_list: list[dict[str, str]]) -> list[dict[str, str]]:
    """Remove duplicate SKU rows while preserving the first useful row."""

    deduped: dict[str, dict[str, str]] = {}
    for sku in sku_list:
        if not isinstance(sku, dict):
            continue

        spec_name = normalize_spec_name(sku.get("spec_name")) or "Default"
        price = str(sku.get("price") or "").strip()
        stock = str(sku.get("stock") or "").strip()
        sku_image = str(sku.get("sku_image") or "").strip()
        key = normalize_lookup_key(spec_name) or f"{price}|{stock}|{sku_image}"

        if key not in deduped:
            deduped[key] = {
                "spec_name": spec_name,
                "price": price,
                "stock": stock,
                "sku_image": sku_image,
            }
            continue

        existing = deduped[key]
        if not existing.get("price") and price:
            existing["price"] = price
        if not existing.get("stock") and stock:
            existing["stock"] = stock
        if not existing.get("sku_image") and sku_image:
            existing["sku_image"] = sku_image

    return list(deduped.values())


def extract_shopee_sku_list(item: dict[str, Any]) -> list[dict[str, str]]:
    """Extract Shopee SKU rows from tier variations and model combinations."""

    tier_variations = item.get("tier_variations") or []
    models = item.get("models") or []
    option_groups = get_tier_option_names(tier_variations if isinstance(tier_variations, list) else [])
    option_images = get_tier_option_images(tier_variations if isinstance(tier_variations, list) else [])
    image_aliases = get_tier_option_image_aliases(tier_variations if isinstance(tier_variations, list) else [])

    rows: list[dict[str, str]] = []
    processed_skus: set[str] = set()
    if isinstance(models, list):
        for model in models:
            if not isinstance(model, dict):
                continue

            spec_name = build_shopee_model_spec(model, option_groups)
            sku_key = shopee_sku_identity(model, spec_name)
            if sku_key in processed_skus:
                continue
            processed_skus.add(sku_key)

            price_value = (
                model.get("price")
                or model.get("price_before_discount")
                or model.get("raw_price")
                or model.get("current_price")
                or model.get("price_min")
                or model.get("price_max")
            )
            price_stocks = model.get("price_stocks")
            if price_value in (None, "", 0) and isinstance(price_stocks, list) and price_stocks:
                first_price_stock = price_stocks[0]
                if isinstance(first_price_stock, dict):
                    price_value = (
                        first_price_stock.get("price")
                        or first_price_stock.get("current_price")
                        or first_price_stock.get("price_before_discount")
                    )

            price = normalize_shopee_price(price_value)
            stock = normalize_stock(
                model.get("stock")
                or model.get("normal_stock")
                or model.get("current_stock")
            )
            sku_image = build_shopee_model_image(model, option_images, image_aliases, spec_name)

            if spec_name:
                rows.append(
                    {
                        "spec_name": spec_name,
                        "price": price or "",
                        "stock": stock,
                        "sku_image": sku_image,
                    }
                )

    if rows:
        return dedupe_sku_rows(rows)

    fallback_price = extract_shopee_base_price(item)

    fallback_images = extract_shopee_images(item)
    return dedupe_sku_rows([
        {
            "spec_name": "Default",
            "price": fallback_price or "",
            "stock": normalize_stock(
                item.get("stock")
                or item.get("normal_stock")
                or item.get("current_stock")
                or item.get("historical_sold")
            ),
            "sku_image": fallback_images[0] if fallback_images else "",
        }
    ])


def extract_shopee_data(raw_data: dict[str, Any]) -> dict[str, Any]:
    """Extract EasyCollect-standard product data from Shopee raw payload.

    This parser deliberately prioritizes the official ``item.images`` array for
    carousel images. Shopee also exposes single cover image fields, but those are
    used only as a last fallback so the export package keeps the full gallery.
    """

    item_data = get_shopee_item_data(raw_data)
    title = normalize_title(item_data.get("name") or item_data.get("title"))
    main_images = extract_shopee_images(item_data) or find_first_shopee_images_array(raw_data)
    sku_list = extract_shopee_sku_list(item_data)
    if not main_images:
        main_images = collect_image_urls(raw_data)
    fill_shopee_sku_image_fallbacks(sku_list, main_images)

    price = extract_shopee_base_price(item_data)
    if is_missing_base_price(price):
        price = infer_price_range_from_skus(sku_list)
    if is_missing_base_price(price):
        price = extract_shopee_dom_price(raw_data, item_data)

    clean_data = {
        "title": title or "",
        "base_price": "" if price is None else str(price),
        "main_images": main_images,
        "sku_list": dedupe_sku_rows(sku_list),
    }
    heal_product_prices(clean_data)
    return {
        "title": clean_data["title"],
        "base_price": clean_data["base_price"],
        "main_images": clean_data["main_images"],
        "sku_list": clean_data["sku_list"],
    }


def build_parsed_product(
    raw_data: Any,
    parsed: dict[str, Any],
    sku_list_override: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Build the compact product JSON saved beside the raw capture.

    Args:
        raw_data: Raw JSON-compatible payload received from the extension.
        parsed: Parsed title, image, and price values from ``parse_raw_product``.

    Returns:
        A normalized dictionary matching ``parsed_product.json`` requirements.
    """

    sku_list = (
        sku_list_override
        if sku_list_override is not None
        else extract_sku_list(raw_data) if isinstance(raw_data, dict) else []
    )

    return {
        "title": parsed.get("title") or "",
        "base_price": "" if parsed.get("price") is None else str(parsed.get("price")),
        "main_images": parsed.get("images") or [],
        "sku_list": sku_list,
    }


async def optimize_product_for_export(parsed_product: dict[str, Any]) -> tuple[dict[str, Any], bool]:
    """Best-effort Kiro Agent optimization used by the one-click collect flow.

    The capture workflow must remain useful even when the LLM provider is not
    configured, times out, or returns invalid JSON. This helper therefore tries
    to create an optimized product package, logs any failure, and falls back to
    the cleaned parsed product so ZIP export can still complete.

    Args:
        parsed_product: Cleaned product dictionary from the 1688 parser.

    Returns:
        A tuple of ``(product_for_export, optimized)``. ``optimized`` is true
        only when the Agent returned valid copy and the optimized cache was
        written successfully.
    """

    try:
        optimized_product = await optimize_parsed_product(parsed_product)
        logger.info("Kiro Agent copy generated for export.")
        return optimized_product, True
    except Exception as exc:
        logger.warning(
            "Kiro Agent optimization skipped; exporting parsed product instead: %s",
            exc,
        )
        return parsed_product, False


def extract_1688_data(raw_data: dict[str, Any]) -> dict[str, Any]:
    """Extract core product fields from volatile 1688 payload structures.

    The 1688 detail page can expose product data through different globals such
    as ``FE_GLOBALS``, direct ``globalData`` objects, or newer ``lofty``-shaped
    containers. This parser first tries high-confidence paths, then falls back to
    recursive key sniffing so small layout changes do not break the MVP pipeline.

    Args:
        raw_data: Raw JSON-compatible dictionary received from the extension.

    Returns:
        A dictionary with normalized ``title``, ``images``, and ``price`` values.
    """

    title_paths = [
        ["result", "data", "productTitle", "fields", "title"],
        ["result", "global", "globalData", "model", "offerDetail", "subject"],
        ["result", "data", "Root", "fields", "dataJson", "tempModel", "offerName"],
        ["globalData", "tempModel", "offerName"],
        ["globalData", "offerName"],
        ["offerDomain", "subject"],
        ["offerDomain", "offerName"],
        ["data", "offer", "title"],
        ["data", "offer", "subject"],
        ["lofty", "offer", "title"],
        ["lofty", "offer", "subject"],
        ["offer", "title"],
        ["offer", "subject"],
        ["FE_GLOBALS", "globalData", "tempModel", "offerName"],
        ["FE_GLOBALS", "offerDomain", "subject"],
    ]
    image_paths = [
        ["result", "data", "Root", "fields", "dataJson", "images"],
        ["result", "global", "globalData", "model", "offerDetail", "imageList"],
        ["result", "global", "globalData", "model", "offerDetail", "mainImageList"],
        ["globalData", "images"],
        ["globalData", "imageList"],
        ["globalData", "mainImages"],
        ["offerDomain", "crossBorderImages"],
        ["offerDomain", "picUrls"],
        ["data", "offer", "images"],
        ["data", "offer", "picUrls"],
        ["lofty", "images"],
        ["lofty", "offer", "images"],
        ["lofty", "offer", "picUrls"],
        ["offer", "images"],
        ["offer", "picUrls"],
        ["FE_GLOBALS", "globalData", "images"],
        ["FE_GLOBALS", "offerDomain", "crossBorderImages"],
        ["FE_GLOBALS", "offerDomain", "picUrls"],
    ]
    price_paths = [
        ["result", "global", "globalData", "model", "tradeModel", "priceDisplay"],
        ["result", "global", "globalData", "model", "tradeModel", "minPrice"],
        ["result", "data", "mainPrice", "fields", "priceModel", "currentPrices"],
        [
            "result",
            "data",
            "mainPrice",
            "fields",
            "finalPriceModel",
            "tradeWithoutPromotion",
            "offerPriceDisplay",
        ],
        ["globalData", "refPrice"],
        ["globalData", "price"],
        ["offerDomain", "tradeModel", "offerPriceRanges"],
        ["offerDomain", "price"],
        ["data", "offer", "price"],
        ["lofty", "offer", "price"],
        ["offer", "price"],
        ["FE_GLOBALS", "globalData", "refPrice"],
        ["FE_GLOBALS", "offerDomain", "price"],
    ]

    title = normalize_title(safe_get_any(raw_data, title_paths))
    if not title:
        title = normalize_title(
            find_first_by_keys(raw_data, ["offerName", "subject", "productTitle", "title", "name"])
        )

    image_candidates = [safe_get(raw_data, path) for path in image_paths]
    images: list[str] = []
    seen_images: set[str] = set()
    for value in image_candidates:
        for image_url in collect_image_urls(value):
            if image_url not in seen_images:
                seen_images.add(image_url)
                images.append(image_url)

    if not images:
        recursive_images = find_first_by_keys(
            raw_data,
            [
                "crossBorderImages",
                "picUrls",
                "images",
                "imageList",
                "mainImages",
                "originalImageURI",
                "originalImageUrl",
            ],
        )
        images = collect_image_urls(recursive_images)

    price = normalize_price(safe_get_any(raw_data, price_paths))
    if price is None:
        price = normalize_price(
            find_first_by_keys(raw_data, ["refPrice", "price", "priceText", "offerPriceRanges"])
        )

    return {
        "title": title,
        "images": images,
        "price": price,
    }


def parse_raw_product(raw: Any) -> dict[str, Any]:
    """Parse title, images, and reference price from a deep 1688 payload.

    The parser first checks known 1688 paths, then falls back to recursive key
    searches so captured globals such as ``FE_GLOBALS`` can still produce useful
    MVP fields while we continue mapping the exact page shape.

    Args:
        raw: Raw JSON-compatible product payload received from the extension.

    Returns:
        A dictionary containing ``title``, ``images``, and ``price`` keys.
    """

    if isinstance(raw, dict):
        extracted = extract_1688_data(raw)
        if extracted["title"] or extracted["images"] or extracted["price"] is not None:
            return extracted

    global_data_nodes = find_values_by_key(raw, "globalData")
    offer_domain_nodes = find_values_by_key(raw, "offerDomain")
    temp_model_nodes = find_values_by_key(raw, "tempModel")
    data_nodes = find_values_by_key(raw, "data")

    if isinstance(raw, dict):
        global_data_nodes.insert(0, raw.get("globalData"))
        offer_domain_nodes.insert(0, raw.get("offerDomain"))
        temp_model_nodes.insert(0, raw.get("tempModel"))
        data_nodes.insert(0, raw.get("data"))

    title_candidates: list[Any] = []
    image_candidates: list[Any] = []
    price_candidates: list[Any] = []

    title_candidates.extend(
        [
            safe_get_any(
                raw,
                [
                    ["FE_GLOBALS", "globalData", "tempModel", "offerName"],
                    ["FE_GLOBALS", "globalData", "offerName"],
                    ["FE_GLOBALS", "offerDomain", "subject"],
                    ["data", "globalData", "tempModel", "offerName"],
                    ["data", "offerDomain", "subject"],
                    ["globalData", "tempModel", "offerName"],
                    ["offerDomain", "subject"],
                ],
            )
        ]
    )
    image_candidates.extend(
        [
            safe_get_any(
                raw,
                [
                    ["FE_GLOBALS", "globalData", "images"],
                    ["FE_GLOBALS", "globalData", "imageList"],
                    ["FE_GLOBALS", "globalData", "mainImages"],
                    ["FE_GLOBALS", "offerDomain", "crossBorderImages"],
                    ["FE_GLOBALS", "offerDomain", "picUrls"],
                    ["data", "globalData", "images"],
                    ["data", "offerDomain", "crossBorderImages"],
                    ["globalData", "images"],
                    ["offerDomain", "crossBorderImages"],
                    ["offerDomain", "picUrls"],
                ],
            )
        ]
    )
    price_candidates.extend(
        [
            safe_get_any(
                raw,
                [
                    ["FE_GLOBALS", "globalData", "refPrice"],
                    ["FE_GLOBALS", "globalData", "price"],
                    ["FE_GLOBALS", "offerDomain", "refPrice"],
                    ["data", "globalData", "refPrice"],
                    ["globalData", "refPrice"],
                ],
            )
        ]
    )

    for node in global_data_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["tempModel", "offerName"]),
                safe_get(node, ["tempModel", "subject"]),
                safe_get(node, ["tempModel", "title"]),
                safe_get(node, ["offerName"]),
                safe_get(node, ["subject"]),
                safe_get(node, ["title"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["picUrls"]),
                safe_get(node, ["mainImages"]),
                safe_get(node, ["detailImages"]),
                safe_get(node, ["productImages"]),
            ]
        )
        price_candidates.extend(
            [
                safe_get(node, ["refPrice"]),
                safe_get(node, ["price"]),
                safe_get(node, ["priceInfo"]),
            ]
        )

    for node in offer_domain_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["subject"]),
                safe_get(node, ["offerName"]),
                safe_get(node, ["title"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["crossBorderImages"]),
                safe_get(node, ["picUrls"]),
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["mainImages"]),
            ]
        )
        price_candidates.extend(
            [
                safe_get(node, ["refPrice"]),
                safe_get(node, ["price"]),
            ]
        )

    for node in temp_model_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["offerName"]),
                safe_get(node, ["subject"]),
                safe_get(node, ["title"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["picUrls"]),
            ]
        )

    for node in data_nodes:
        title_candidates.extend(
            [
                safe_get(node, ["tempModel", "offerName"]),
                safe_get(node, ["offerName"]),
                safe_get(node, ["subject"]),
            ]
        )
        image_candidates.extend(
            [
                safe_get(node, ["images"]),
                safe_get(node, ["imageList"]),
                safe_get(node, ["picUrls"]),
                safe_get(node, ["crossBorderImages"]),
            ]
        )
        price_candidates.extend(
            [
                safe_get(node, ["refPrice"]),
                safe_get(node, ["price"]),
                safe_get(node, ["priceInfo"]),
            ]
        )

    title = next(
        (normalized for value in title_candidates if (normalized := normalize_title(value))),
        None,
    )
    if not title:
        title = normalize_title(
            find_first_by_keys(raw, ["offerName", "subject", "productTitle", "title", "name"])
        )

    images: list[str] = []
    seen_images: set[str] = set()
    for value in image_candidates:
        for image_url in collect_image_urls(value):
            if image_url not in seen_images:
                seen_images.add(image_url)
                images.append(image_url)

    if not images:
        recursive_images = find_first_by_keys(
            raw,
            [
                "crossBorderImages",
                "picUrls",
                "images",
                "imageList",
                "mainImages",
                "detailImages",
                "productImages",
            ],
        )
        images = collect_image_urls(recursive_images)

    price = next(
        (normalized for value in price_candidates if (normalized := normalize_price(value)) is not None),
        None,
    )
    if price is None:
        price = normalize_price(find_first_by_keys(raw, ["refPrice", "price", "priceText"]))

    return {
        "title": title,
        "images": images,
        "price": price,
    }


def normalize_platform(source: str | None, platform: str | None, url: str | None) -> str:
    """Normalize the frontend platform marker into an internal route key."""

    for value in [platform, source, url]:
        if not value:
            continue

        lowered = value.lower()
        if "shopee" in lowered:
            return "shopee"
        if "1688" in lowered:
            return "1688"

    return "1688"


def parse_product_by_platform(
    raw: Any,
    platform: str,
) -> dict[str, Any]:
    """Route raw product payloads to the correct marketplace parser."""

    if platform == "shopee" and isinstance(raw, dict):
        return extract_shopee_data(raw)

    parsed = parse_raw_product(raw)
    return {
        "title": parsed.get("title") or "",
        "base_price": "" if parsed.get("price") is None else str(parsed.get("price")),
        "main_images": parsed.get("images") or [],
        "sku_list": extract_sku_list(raw) if isinstance(raw, dict) else [],
    }


def create_app() -> FastAPI:
    """Create and configure the EasyCollect FastAPI application.

    The MVP backend keeps the architecture intentionally light. It mounts the
    local ``app/static`` directory at ``/static`` so cached product images can be
    previewed directly from FastAPI, enables CORS for Vite and Chrome extension
    origins during development, and registers minimal health and collection
    endpoints for the first browser-extension integration test.

    Returns:
        A configured ``FastAPI`` application instance ready for Uvicorn.
    """

    STATIC_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(level=logging.INFO)

    app = FastAPI(
        title="EasyCollect API",
        description="EasyCollect backend data hub and Agent engine",
        version="0.1.0",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=[
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ],
        allow_origin_regex=r"chrome-extension://.*",
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
    product_store.init_product_db()
    app.include_router(export_router)
    app.include_router(optimize_router)
    app.include_router(shopee_router)

    @app.get("/health", response_model=HealthResponse)
    async def health_check() -> HealthResponse:
        """Return the current API service health state.

        The browser extension and local development tools can call this endpoint
        before posting collected product data. It also verifies that the
        application has created and mounted the local static-media directory.

        Returns:
            A ``HealthResponse`` object containing service and static path info.
        """

        return HealthResponse(
            status="ok",
            service="easycollect-server",
            static_url="/static",
        )

    @app.get("/api/products", response_model=ProductSummaryResponse)
    async def list_products(platform: str | None = None) -> ProductSummaryResponse:
        """Return locally cached parsed/optimized products for the dashboard."""

        products = product_store.list_products(platform)
        if not products and platform is None:
            products = list_local_product_summaries()
        return ProductSummaryResponse(products=products)

    @app.delete("/api/products/bulk")
    async def delete_products_bulk(request: BulkProductDeleteRequest) -> JSONResponse:
        """Delete selected product-library rows in one request."""

        clean_ids = [product_id for product_id in request.product_ids if product_id]
        if not clean_ids:
            raise HTTPException(status_code=400, detail="请选择要删除的商品")

        deleted_count = product_store.delete_products(clean_ids)
        return JSONResponse(
            content={
                "status": "success",
                "deleted_count": deleted_count,
                "message": f"已删除 {deleted_count} 个商品",
            },
            media_type="application/json; charset=utf-8",
        )

    @app.delete("/api/products/clear")
    async def clear_products() -> JSONResponse:
        """Clear every product-library row from the local SQLite inbox."""

        deleted_count = product_store.clear_products()
        return JSONResponse(
            content={
                "status": "success",
                "deleted_count": deleted_count,
                "message": "商品库已清空",
            },
            media_type="application/json; charset=utf-8",
        )

    @app.delete("/api/products/{product_id}")
    async def delete_product(product_id: str) -> dict[str, str]:
        """Delete one local product cache file by dashboard row id."""

        if product_store.delete_product(product_id):
            return {"status": "success", "msg": "Product deleted."}

        allowed_files = {
            "parsed_product": PARSED_PRODUCT_PATH,
            "optimized_product": CACHE_DATA_DIR / "optimized_product.json",
        }
        cache_path = allowed_files.get(product_id)
        if cache_path is None:
            raise HTTPException(status_code=404, detail="Product cache not found.")

        if cache_path.exists():
            cache_path.unlink()

        return {"status": "success", "msg": "Product deleted."}

    @app.post("/api/collect", response_model=CollectResponse)
    async def collect_product(
        payload: CollectRequest,
    ) -> CollectResponse:
        """Accept raw product detail data captured from a marketplace page.

        During Stage 3 this endpoint persists the latest raw payload for local
        structure inspection, parses common 1688 product fields from deep globals
        such as ``FE_GLOBALS``, and returns the parsed MVP fields to the browser
        extension for end-to-end validation.

        Args:
            payload: Pydantic-validated raw capture payload sent by the extension
                service worker.

        Returns:
            A ``CollectResponse`` confirming that the payload reached the backend.
        """

        raw_file = dump_raw_payload(payload.raw)
        platform = normalize_platform(payload.source, payload.platform, payload.url)
        parsed_product = parse_product_by_platform(payload.raw, platform)
        heal_product_prices(parsed_product)

        title = parsed_product.get("title") or payload.title
        images = parsed_product.get("main_images") or payload.images
        price = parsed_product.get("base_price")
        parsed_product["title"] = title or ""
        parsed_product["main_images"] = images
        parsed_product["base_price"] = "" if price is None else str(price)
        heal_product_prices(parsed_product)
        parsed_file = dump_parsed_product(parsed_product)
        if payload.ai_mode:
            product_for_storage, optimized = await optimize_product_for_export(parsed_product)
        else:
            product_for_storage, optimized = parsed_product, False

        product_for_storage.setdefault("source_title", parsed_product.get("title", ""))
        product_for_storage.setdefault("base_price", parsed_product.get("base_price", ""))
        product_for_storage.setdefault("main_images", parsed_product.get("main_images", []))
        product_for_storage.setdefault("sku_list", parsed_product.get("sku_list", []))
        product_for_storage["platform"] = platform
        product_id = product_store.save_product(
            product_for_storage,
            raw=payload.raw,
            platform=platform,
        )

        logger.info("Received EasyCollect payload from %s", payload.source)
        logger.info("Platform: %s", platform)
        logger.info("URL: %s", payload.url)
        logger.info("Data key: %s", payload.dataKey or "unknown")
        logger.info("AI mode: %s", payload.ai_mode)
        logger.info("Raw payload saved: %s", raw_file)
        logger.info("Parsed product saved: %s", parsed_file)
        logger.info("Agent optimized product: %s", optimized)
        logger.info("Product library id: %s", product_id)
        logger.info("Title: %s", title or "not found")
        logger.info("Price: %s", price or "not found")
        logger.info("Images: %s", images[:10])
        logger.info("Image count: %s", len(images))
        logger.info("SKU count: %s", len(parsed_product["sku_list"]))

        response_content = {
            "status": "success",
            "msg": "商品已成功入库！",
            "message": "商品已成功入库！",
            "title": title,
            "images": images,
            "price": price,
            "product_id": product_id,
            "raw_file": str(raw_file),
            "parsed_file": str(parsed_file),
            "optimized": optimized,
        }
        return JSONResponse(
            content=response_content,
            media_type="application/json; charset=utf-8",
        )

    return app


app = create_app()
