import asyncio
import json
import logging
import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from fastapi import APIRouter, HTTPException
from openai import APITimeoutError, AsyncOpenAI
from pydantic import BaseModel, ConfigDict, Field, ValidationError


BASE_DIR = Path(__file__).resolve().parents[2]
CACHE_DIR = BASE_DIR / "static" / "cache_data"
PARSED_PRODUCT_PATH = CACHE_DIR / "parsed_product.json"
OPTIMIZED_PRODUCT_PATH = CACHE_DIR / "optimized_product.json"

load_dotenv(BASE_DIR / ".env")

router = APIRouter()
logger = logging.getLogger("easycollect")

PRIMARY_API_KEY = os.getenv("PRIMARY_API_KEY")
PRIMARY_BASE_URL = os.getenv("PRIMARY_BASE_URL", "https://api2.apiaqi.com/v1")
PRIMARY_MODEL_NAME = os.getenv("PRIMARY_MODEL_NAME", "gpt-4o")

FALLBACK_API_KEY = os.getenv("FALLBACK_API_KEY")
FALLBACK_BASE_URL = os.getenv("FALLBACK_BASE_URL", "https://api.deepseek.com/v1")
FALLBACK_MODEL_NAME = os.getenv("FALLBACK_MODEL_NAME", "deepseek-chat")
LLM_TIMEOUT_SECONDS = 15.0

KIRO_SYSTEM_PROMPT = """
You are a senior cross-border ecommerce localization and conversion expert.
Your task is to transform rough 1688 wholesale product data into polished,
retail-ready listing content for overseas ecommerce platforms.

Rules:
1. Remove wholesale traces such as factory direct, mixed batch, dropshipping,
   and supplier-facing language.
2. Use refined, consumer-friendly language that highlights quality, use case,
   lifestyle, and purchase confidence.
3. Rewrite SKU names into short buyer-facing names. Remove redundant factory
   codes, noisy symbols, and repeated size/color wording when possible.
4. Output JSON only. Do not include markdown fences or explanatory text.
5. You must use exactly these top-level keys:
   title_optimized, marketing_copy, bullet_points, platform_tags, sku_list.
6. Never output keys named title, stock, price, sku_image, base_price,
   source_title, main_images, or any other extra key. Price, stock, and images
   are deterministic backend fields and will be merged by code after your reply.
7. Every sku_list item must contain exactly one key: spec_name.

Required JSON example:
{
  "title_optimized": "Elegant Zircon Tennis Bracelet for Everyday Sparkle",
  "marketing_copy": "Add a polished finishing touch to daily outfits with a lightweight bracelet designed for effortless shine.",
  "bullet_points": [
    "Brilliant zircon accents for a refined look",
    "Comfortable for daily wear and gifting",
    "Easy to style with casual or evening outfits"
  ],
  "platform_tags": [
    "zircon bracelet",
    "tennis bracelet",
    "women jewelry",
    "gift bracelet"
  ],
  "sku_list": [
    {
      "spec_name": "Silver Tone"
    },
    {
      "spec_name": "Gold Tone"
    }
  ]
}
"""


class SKURetail(BaseModel):
    """Validated retail-facing SKU row returned by the Kiro Agent."""

    model_config = ConfigDict(extra="forbid")

    spec_name: str = Field(description="Clear retail-facing SKU name.")


class OptimizedProduct(BaseModel):
    """Validated optimized product payload returned by the Kiro Agent."""

    model_config = ConfigDict(extra="forbid")

    title_optimized: str = Field(
        description="SEO-optimized retail title within 60 characters."
    )
    marketing_copy: str = Field(description="High-conversion ecommerce copy.")
    bullet_points: list[str] = Field(description="Three to five selling points.")
    platform_tags: list[str] = Field(
        description="Search tags and long-tail ecommerce keywords."
    )
    sku_list: list[SKURetail] = Field(description="Retail-cleaned SKU list.")


def ensure_llm_config() -> None:
    """Validate that both primary and fallback LLM API keys are configured.

    Raises:
        HTTPException: Raised when either API key is missing.
    """

    missing_keys = []
    if not PRIMARY_API_KEY or PRIMARY_API_KEY.startswith("sk-fill-"):
        missing_keys.append("PRIMARY_API_KEY")
    if not FALLBACK_API_KEY or FALLBACK_API_KEY.startswith("sk-fill-"):
        missing_keys.append("FALLBACK_API_KEY")

    if missing_keys:
        raise HTTPException(
            status_code=500,
            detail=f"Missing LLM environment variables: {', '.join(missing_keys)}",
        )


def create_llm_client(api_key: str | None, base_url: str) -> AsyncOpenAI:
    """Create an OpenAI-compatible async client with a strict timeout.

    Args:
        api_key: API key loaded from environment variables.
        base_url: OpenAI-compatible API base URL.

    Returns:
        A configured ``AsyncOpenAI`` client.
    """

    return AsyncOpenAI(
        api_key=api_key,
        base_url=base_url,
        timeout=LLM_TIMEOUT_SECONDS,
    )


def read_parsed_product() -> dict[str, Any]:
    """Load the cleaned product JSON generated by the collection endpoint.

    Returns:
        The parsed product dictionary from ``parsed_product.json``.

    Raises:
        HTTPException: Raised when the parsed product cache is missing or invalid.
    """

    if not PARSED_PRODUCT_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail="parsed_product.json not found. Run the collection flow first.",
        )

    try:
        with PARSED_PRODUCT_PATH.open("r", encoding="utf-8") as file:
            data = json.load(file)
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=f"parsed_product.json is not valid JSON: {exc}",
        ) from exc

    if not isinstance(data, dict):
        raise HTTPException(
            status_code=500,
            detail="parsed_product.json must contain a JSON object.",
        )

    return data


def build_llm_input(parsed_data: dict[str, Any]) -> dict[str, Any]:
    """Build the compact prompt payload sent to the Kiro Agent.

    Image URLs are intentionally excluded from the prompt to save tokens. They
    are merged back into the final optimized payload after model validation.

    Args:
        parsed_data: Cleaned product data from ``parsed_product.json``.

    Returns:
        A compact dictionary containing fields needed for copywriting.
    """

    return {
        "original_title": parsed_data.get("title", ""),
        "base_price": parsed_data.get("base_price", ""),
        "sku_list": [
            {
                "spec_name": sku.get("spec_name", ""),
                "price": sku.get("price", ""),
                "stock": sku.get("stock", ""),
            }
            for sku in parsed_data.get("sku_list", [])
            if isinstance(sku, dict)
        ],
    }


async def request_json_completion(
    client: AsyncOpenAI,
    model: str,
    messages: list[dict[str, str]],
) -> dict[str, Any]:
    """Request a JSON object response from an OpenAI-compatible endpoint.

    Args:
        client: Configured OpenAI-compatible async client.
        model: Model name to request.
        messages: Chat messages sent to the model.

    Returns:
        The parsed JSON object returned by the model.

    Raises:
        ValueError: Raised when the model returns empty or non-object JSON.
        json.JSONDecodeError: Raised when the model returns malformed JSON.
    """

    response = await client.chat.completions.create(
        model=model,
        messages=messages,
        response_format={"type": "json_object"},
        temperature=0.7,
        timeout=LLM_TIMEOUT_SECONDS,
    )
    content = response.choices[0].message.content

    if not content:
        raise ValueError("LLM returned an empty response.")

    parsed = json.loads(content)
    if not isinstance(parsed, dict):
        raise ValueError("LLM returned JSON, but it was not an object.")

    return parsed


async def call_llm_with_fallback(system_prompt: str, user_content: str) -> dict[str, Any]:
    """Call the primary LLM provider and fall back to DeepSeek on failure.

    Args:
        system_prompt: System instruction used by the Kiro Agent.
        user_content: Product-specific user prompt.

    Returns:
        The JSON object generated by the first available model provider.

    Raises:
        RuntimeError: Raised when both primary and fallback channels fail.
    """

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    try:
        logger.info("Requesting primary LLM provider: %s", PRIMARY_BASE_URL)
        return await request_json_completion(
            client=create_llm_client(PRIMARY_API_KEY, PRIMARY_BASE_URL),
            model=PRIMARY_MODEL_NAME,
            messages=messages,
        )
    except Exception as primary_exc:
        logger.warning("Primary LLM request failed: %s", primary_exc)

    try:
        logger.info("Requesting fallback LLM provider: %s", FALLBACK_BASE_URL)
        return await request_json_completion(
            client=create_llm_client(FALLBACK_API_KEY, FALLBACK_BASE_URL),
            model=FALLBACK_MODEL_NAME,
            messages=messages,
        )
    except Exception as fallback_exc:
        logger.error("Fallback LLM request failed: %s", fallback_exc)
        raise RuntimeError(
            "All LLM channels are unavailable. Check network and API keys."
        ) from fallback_exc


def merge_optimized_product(
    optimized: OptimizedProduct,
    parsed_data: dict[str, Any],
) -> dict[str, Any]:
    """Merge model-generated copy with deterministic product assets.

    Args:
        optimized: Validated model output.
        parsed_data: Local cleaned product data containing images and raw SKUs.

    Returns:
        Final optimized product dictionary written to disk.
    """

    final_product = optimized.model_dump()
    source_skus = [
        sku
        for sku in parsed_data.get("sku_list", [])
        if isinstance(sku, dict)
    ]
    merged_skus = []

    for index, source_sku in enumerate(source_skus):
        optimized_sku = (
            final_product["sku_list"][index]
            if index < len(final_product["sku_list"])
            else {}
        )
        merged_skus.append(
            {
                "spec_name": optimized_sku.get("spec_name")
                or source_sku.get("spec_name", ""),
                "price": source_sku.get("price", ""),
                "stock": source_sku.get("stock", ""),
                "sku_image": source_sku.get("sku_image", ""),
            }
        )

    final_product["sku_list"] = merged_skus
    final_product["main_images"] = parsed_data.get("main_images", [])
    final_product["source_title"] = parsed_data.get("title", "")
    final_product["base_price"] = parsed_data.get("base_price", "")
    return final_product


def dump_optimized_product(final_product: dict[str, Any]) -> Path:
    """Persist the final Agent-optimized product JSON.

    Args:
        final_product: Validated and merged optimized product payload.

    Returns:
        Path to ``optimized_product.json``.
    """

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    with OPTIMIZED_PRODUCT_PATH.open("w", encoding="utf-8") as file:
        json.dump(final_product, file, indent=2, ensure_ascii=False)

    return OPTIMIZED_PRODUCT_PATH


def build_fallback_optimized_product(
    parsed_data: dict[str, Any],
    reason: str,
) -> dict[str, Any]:
    """Build a safe optimized-product fallback when the LLM path fails.

    Args:
        parsed_data: Cleaned product data generated by the parser.
        reason: Short failure reason for logs and local JSON inspection.

    Returns:
        A product dictionary shaped like ``optimized_product.json``.
    """

    title = str(parsed_data.get("title") or "").strip() or "EasyCollect Product"
    return {
        "title_optimized": title,
        "marketing_copy": (
            "AI \u751f\u6210\u8d85\u65f6\u6216\u7f51\u7edc\u62e5\u5835\uff0c"
            "\u8bf7\u7a0d\u540e\u5728\u540e\u53f0\u91cd\u65b0\u751f\u6210\u3002"
        ),
        "bullet_points": [
            "\u6682\u65e0 AI \u5356\u70b9\uff0c\u5df2\u4fdd\u7559\u539f\u59cb\u91c7\u96c6\u6570\u636e\u3002"
        ],
        "platform_tags": ["\u6682\u65e0\u6807\u7b7e"],
        "sku_list": [
            sku
            for sku in parsed_data.get("sku_list", [])
            if isinstance(sku, dict)
        ],
        "main_images": parsed_data.get("main_images", []),
        "source_title": title,
        "base_price": parsed_data.get("base_price", ""),
        "optimization_status": "fallback",
        "optimization_error": reason,
    }


async def optimize_parsed_product(parsed_data: dict[str, Any]) -> dict[str, Any]:
    """Run the Kiro Agent with hard timeout and graceful fallback.

    Args:
        parsed_data: Cleaned product data generated by the collection parser.

    Returns:
        Optimized product data when the model succeeds, otherwise a fallback
        object that preserves the original title, images, price, and SKUs.
    """

    try:
        ensure_llm_config()
        llm_input = build_llm_input(parsed_data)
        user_content = (
            "Optimize this product data for overseas ecommerce retail:\n"
            f"{json.dumps(llm_input, ensure_ascii=False, indent=2)}"
        )
        raw_json_result = await asyncio.wait_for(
            call_llm_with_fallback(KIRO_SYSTEM_PROMPT, user_content),
            timeout=LLM_TIMEOUT_SECONDS,
        )
        validated_data = OptimizedProduct.model_validate(raw_json_result)
        final_product = merge_optimized_product(validated_data, parsed_data)
        final_product["optimization_status"] = "success"
    except (asyncio.TimeoutError, APITimeoutError) as exc:
        logger.warning(
            "LLM optimization timed out after %.1fs: %s",
            LLM_TIMEOUT_SECONDS,
            exc,
        )
        final_product = build_fallback_optimized_product(parsed_data, "llm_timeout")
    except ValidationError as exc:
        logger.warning("LLM output validation failed: %s", exc)
        final_product = build_fallback_optimized_product(parsed_data, "validation_error")
    except Exception as exc:
        logger.warning("LLM optimization failed: %s", exc)
        final_product = build_fallback_optimized_product(parsed_data, str(exc))

    dump_optimized_product(final_product)
    return final_product


@router.post("/api/optimize")
async def optimize_product_data() -> dict[str, Any]:
    """Optimize the cleaned 1688 product cache with the Kiro Agent.

    Returns:
        A response containing final optimized or fallback product data.
    """

    parsed_data = read_parsed_product()
    final_product = await optimize_parsed_product(parsed_data)
    logger.info("Agent optimization finished: %s", OPTIMIZED_PRODUCT_PATH)
    return {
        "status": "success",
        "optimized_file": str(OPTIMIZED_PRODUCT_PATH),
        "data": final_product,
    }
